/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageproduk;

import meuli.adminHome;

/**
 *
 * @author thero
 */
public class ubahHargaProdukFrame extends javax.swing.JFrame {

    /**
     * Creates new form ubahHargaProdukFrame
     */
    public ubahHargaProdukFrame() {
        initComponents();
       setHarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert1 = new javax.swing.JOptionPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lblhargabukubelajar = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        lblhargabukucerita = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        lblhargabumbu = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jmlbesokap = new javax.swing.JTextField();
        jmlblankon = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jmlbros = new javax.swing.JTextField();
        jmlbukubelajar = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        jmlbukucerita = new javax.swing.JTextField();
        jButton34 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jmlbumbu = new javax.swing.JTextField();
        jButton35 = new javax.swing.JButton();
        jmlangklung = new javax.swing.JTextField();
        lblhargabros = new javax.swing.JLabel();
        lblhargablankon = new javax.swing.JLabel();
        lblhargabesokap = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblhargaangklung222 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblhargaangklung = new javax.swing.JLabel();
        lblhargaangklung2 = new javax.swing.JLabel();
        lblhargaangklung3 = new javax.swing.JLabel();
        lblhargaangklung4 = new javax.swing.JLabel();
        lblhargaangklung5 = new javax.swing.JLabel();
        lblhargaangklung6 = new javax.swing.JLabel();
        lblhargaangklung7 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        lblhargacelengan = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        lblhargaiket = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        lblhargakamus = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        lblhargakaos = new javax.swing.JLabel();
        lblhargakecapi = new javax.swing.JLabel();
        lblhargakopi = new javax.swing.JLabel();
        jmlliwet = new javax.swing.JTextField();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jmlkopi = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jmlkecapi = new javax.swing.JTextField();
        jButton39 = new javax.swing.JButton();
        jmlkaos = new javax.swing.JTextField();
        jButton40 = new javax.swing.JButton();
        jmlkamus = new javax.swing.JTextField();
        jButton41 = new javax.swing.JButton();
        jmliket = new javax.swing.JTextField();
        jButton42 = new javax.swing.JButton();
        jmlcelengan = new javax.swing.JTextField();
        lblhargaliwet = new javax.swing.JLabel();
        lblhargaangklung8 = new javax.swing.JLabel();
        lblhargaangklung9 = new javax.swing.JLabel();
        lblhargaangklung10 = new javax.swing.JLabel();
        lblhargaangklung11 = new javax.swing.JLabel();
        lblhargaangklung12 = new javax.swing.JLabel();
        lblhargaangklung13 = new javax.swing.JLabel();
        lblhargaangklung14 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        lblhargamahkota = new javax.swing.JLabel();
        lblhargapangrumat = new javax.swing.JLabel();
        lblhargapangsi = new javax.swing.JLabel();
        lblhargaperang = new javax.swing.JLabel();
        lblhargapisang = new javax.swing.JLabel();
        lblhargapusaka = new javax.swing.JLabel();
        lblhargarumah = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jmlrumah = new javax.swing.JTextField();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jmlpusaka = new javax.swing.JTextField();
        jButton45 = new javax.swing.JButton();
        jmlpisang = new javax.swing.JTextField();
        jButton46 = new javax.swing.JButton();
        jmlperang = new javax.swing.JTextField();
        jButton47 = new javax.swing.JButton();
        jmlpangsi = new javax.swing.JTextField();
        jButton48 = new javax.swing.JButton();
        jmlpangrumat = new javax.swing.JTextField();
        jButton49 = new javax.swing.JButton();
        jmlmahkota = new javax.swing.JTextField();
        lblhargaangklung15 = new javax.swing.JLabel();
        lblhargaangklung16 = new javax.swing.JLabel();
        lblhargaangklung17 = new javax.swing.JLabel();
        lblhargaangklung18 = new javax.swing.JLabel();
        lblhargaangklung19 = new javax.swing.JLabel();
        lblhargaangklung20 = new javax.swing.JLabel();
        lblhargaangklung21 = new javax.swing.JLabel();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        lblhargasasakala = new javax.swing.JLabel();
        lblhargasiger = new javax.swing.JLabel();
        lblhargasimpay = new javax.swing.JLabel();
        lblhargasuling = new javax.swing.JLabel();
        lblhargatales = new javax.swing.JLabel();
        lblhargatotopong = new javax.swing.JLabel();
        lblhargaudeng = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jmludeng = new javax.swing.JTextField();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jmltotopong = new javax.swing.JTextField();
        jButton59 = new javax.swing.JButton();
        jmltales = new javax.swing.JTextField();
        jButton60 = new javax.swing.JButton();
        jmlsuling = new javax.swing.JTextField();
        jButton61 = new javax.swing.JButton();
        jmlsimpay = new javax.swing.JTextField();
        jButton62 = new javax.swing.JButton();
        jmlsiger = new javax.swing.JTextField();
        jButton63 = new javax.swing.JButton();
        jmlsasakala = new javax.swing.JTextField();
        lblhargaangklung22 = new javax.swing.JLabel();
        lblhargaangklung23 = new javax.swing.JLabel();
        lblhargaangklung24 = new javax.swing.JLabel();
        lblhargaangklung25 = new javax.swing.JLabel();
        lblhargaangklung26 = new javax.swing.JLabel();
        lblhargaangklung27 = new javax.swing.JLabel();
        lblhargaangklung28 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 1000));
        setPreferredSize(new java.awt.Dimension(1100, 900));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/broskujang50000.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 70, 130, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/angklung25000.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 70, 130, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/beskap115000.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 70, 130, 100);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/blankonSunda90000.png"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(300, 70, 130, 100);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bukubelajar25000.png"))); // NOI18N
        getContentPane().add(jButton5);
        jButton5.setBounds(580, 70, 130, 100);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Buku Belajar");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(580, 40, 110, 30);

        lblhargabukubelajar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabukubelajar.setText("Rp. 25.000");
        getContentPane().add(lblhargabukubelajar);
        lblhargabukubelajar.setBounds(650, 170, 60, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bukucerita25000.png"))); // NOI18N
        getContentPane().add(jButton6);
        jButton6.setBounds(720, 70, 130, 100);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Buku Cerita");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(720, 40, 110, 30);

        lblhargabukucerita.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabukucerita.setText("Rp. 25.000");
        getContentPane().add(lblhargabukucerita);
        lblhargabukucerita.setBounds(790, 170, 60, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Bumbu");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(860, 40, 100, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bumbuNasgor30000.png"))); // NOI18N
        getContentPane().add(jButton7);
        jButton7.setBounds(860, 70, 130, 100);

        lblhargabumbu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabumbu.setText("Rp. 25.000");
        getContentPane().add(lblhargabumbu);
        lblhargabumbu.setBounds(930, 170, 60, 20);

        jButton29.setText("Ubah");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(20, 220, 130, 20);

        jmlbesokap.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbesokap.setText("0");
        getContentPane().add(jmlbesokap);
        jmlbesokap.setBounds(160, 190, 130, 20);

        jmlblankon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlblankon.setText("0");
        getContentPane().add(jmlblankon);
        jmlblankon.setBounds(300, 190, 130, 20);

        jButton31.setText("Ubah");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(300, 220, 130, 20);

        jButton30.setText("Ubah");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(160, 220, 130, 20);

        jmlbros.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbros.setText("0");
        getContentPane().add(jmlbros);
        jmlbros.setBounds(440, 190, 130, 20);

        jmlbukubelajar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbukubelajar.setText("0");
        getContentPane().add(jmlbukubelajar);
        jmlbukubelajar.setBounds(580, 190, 130, 20);

        jButton33.setText("Ubah");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(580, 220, 130, 20);

        jmlbukucerita.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbukucerita.setText("0");
        getContentPane().add(jmlbukucerita);
        jmlbukucerita.setBounds(720, 190, 130, 20);

        jButton34.setText("Ubah");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(720, 220, 130, 20);

        jButton32.setText("Ubah");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(440, 220, 130, 20);

        jmlbumbu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbumbu.setText("0");
        getContentPane().add(jmlbumbu);
        jmlbumbu.setBounds(860, 190, 130, 20);

        jButton35.setText("Ubah");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(860, 220, 130, 20);

        jmlangklung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlangklung.setText("0");
        jmlangklung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlangklungActionPerformed(evt);
            }
        });
        getContentPane().add(jmlangklung);
        jmlangklung.setBounds(20, 190, 130, 20);

        lblhargabros.setText("Rp. 25.000");
        getContentPane().add(lblhargabros);
        lblhargabros.setBounds(510, 170, 60, 20);

        lblhargablankon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargablankon.setText("Rp. 25.000");
        getContentPane().add(lblhargablankon);
        lblhargablankon.setBounds(370, 170, 60, 20);

        lblhargabesokap.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabesokap.setText("Rp. 25.000");
        getContentPane().add(lblhargabesokap);
        lblhargabesokap.setBounds(220, 170, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bros");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 40, 50, 30);

        lblhargaangklung222.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung222.setText("Harga Lama");
        getContentPane().add(lblhargaangklung222);
        lblhargaangklung222.setBounds(860, 170, 60, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Blankon");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 40, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Angklung");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 40, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Besokap");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 40, 90, 30);

        lblhargaangklung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung.setText("0");
        getContentPane().add(lblhargaangklung);
        lblhargaangklung.setBounds(80, 170, 70, 20);

        lblhargaangklung2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung2.setText("Harga Lama");
        getContentPane().add(lblhargaangklung2);
        lblhargaangklung2.setBounds(860, 380, 60, 20);

        lblhargaangklung3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung3.setText("Harga Lama");
        getContentPane().add(lblhargaangklung3);
        lblhargaangklung3.setBounds(160, 170, 60, 20);

        lblhargaangklung4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung4.setText("Harga Lama");
        getContentPane().add(lblhargaangklung4);
        lblhargaangklung4.setBounds(300, 170, 60, 20);

        lblhargaangklung5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung5.setText("Harga Lama");
        getContentPane().add(lblhargaangklung5);
        lblhargaangklung5.setBounds(440, 170, 60, 20);

        lblhargaangklung6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung6.setText("Harga Lama");
        getContentPane().add(lblhargaangklung6);
        lblhargaangklung6.setBounds(580, 170, 60, 20);

        lblhargaangklung7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung7.setText("Harga Lama");
        getContentPane().add(lblhargaangklung7);
        lblhargaangklung7.setBounds(720, 170, 60, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Celengan");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(20, 250, 100, 30);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/celengan1600.png"))); // NOI18N
        getContentPane().add(jButton15);
        jButton15.setBounds(20, 280, 130, 100);

        lblhargacelengan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargacelengan.setText("Rp. 25.000");
        getContentPane().add(lblhargacelengan);
        lblhargacelengan.setBounds(90, 380, 60, 20);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/iketMaung60000.png"))); // NOI18N
        getContentPane().add(jButton16);
        jButton16.setBounds(160, 280, 130, 100);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Iket");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(160, 250, 120, 30);

        lblhargaiket.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaiket.setText("Rp. 25.000");
        getContentPane().add(lblhargaiket);
        lblhargaiket.setBounds(230, 380, 60, 20);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kamus20000.png"))); // NOI18N
        getContentPane().add(jButton17);
        jButton17.setBounds(300, 280, 130, 100);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Kamus");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(300, 250, 50, 30);

        lblhargakamus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakamus.setText("Rp. 25.000");
        getContentPane().add(lblhargakamus);
        lblhargakamus.setBounds(370, 380, 60, 20);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kaosSunda65000.png"))); // NOI18N
        getContentPane().add(jButton18);
        jButton18.setBounds(440, 280, 130, 100);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Kaos");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(440, 250, 90, 30);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kecapi350000.png"))); // NOI18N
        getContentPane().add(jButton19);
        jButton19.setBounds(580, 280, 130, 100);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Kecapi");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(580, 250, 90, 30);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/KopiSundaGulali85000.png"))); // NOI18N
        getContentPane().add(jButton20);
        jButton20.setBounds(720, 280, 130, 100);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Kopi");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(720, 250, 50, 30);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/liwet19000.png"))); // NOI18N
        getContentPane().add(jButton21);
        jButton21.setBounds(860, 280, 130, 100);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("Liwet");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(860, 250, 100, 30);

        lblhargakaos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakaos.setText("Rp. 25.000");
        getContentPane().add(lblhargakaos);
        lblhargakaos.setBounds(510, 380, 60, 20);

        lblhargakecapi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakecapi.setText("Rp. 25.000");
        getContentPane().add(lblhargakecapi);
        lblhargakecapi.setBounds(650, 380, 60, 20);

        lblhargakopi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakopi.setText("Rp. 25.000");
        getContentPane().add(lblhargakopi);
        lblhargakopi.setBounds(790, 380, 60, 20);

        jmlliwet.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlliwet.setText("0");
        getContentPane().add(jmlliwet);
        jmlliwet.setBounds(860, 400, 130, 20);

        jButton36.setText("Ubah");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(860, 430, 130, 20);

        jButton37.setText("Ubah");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37);
        jButton37.setBounds(720, 430, 130, 20);

        jmlkopi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkopi.setText("0");
        getContentPane().add(jmlkopi);
        jmlkopi.setBounds(720, 400, 130, 20);

        jButton38.setText("Ubah");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38);
        jButton38.setBounds(580, 430, 130, 20);

        jmlkecapi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkecapi.setText("0");
        getContentPane().add(jmlkecapi);
        jmlkecapi.setBounds(580, 400, 130, 20);

        jButton39.setText("Ubah");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton39);
        jButton39.setBounds(440, 430, 130, 20);

        jmlkaos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkaos.setText("0");
        getContentPane().add(jmlkaos);
        jmlkaos.setBounds(440, 400, 130, 20);

        jButton40.setText("Ubah");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton40);
        jButton40.setBounds(300, 430, 130, 20);

        jmlkamus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkamus.setText("0");
        getContentPane().add(jmlkamus);
        jmlkamus.setBounds(300, 400, 130, 20);

        jButton41.setText("Ubah");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41);
        jButton41.setBounds(160, 430, 130, 20);

        jmliket.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmliket.setText("0");
        getContentPane().add(jmliket);
        jmliket.setBounds(160, 400, 130, 20);

        jButton42.setText("Ubah");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton42);
        jButton42.setBounds(20, 430, 130, 20);

        jmlcelengan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlcelengan.setText("0");
        getContentPane().add(jmlcelengan);
        jmlcelengan.setBounds(20, 400, 130, 20);

        lblhargaliwet.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaliwet.setText("Rp. 25.000");
        getContentPane().add(lblhargaliwet);
        lblhargaliwet.setBounds(930, 380, 60, 20);

        lblhargaangklung8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung8.setText("Harga Lama");
        getContentPane().add(lblhargaangklung8);
        lblhargaangklung8.setBounds(20, 170, 60, 20);

        lblhargaangklung9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung9.setText("Harga Lama");
        getContentPane().add(lblhargaangklung9);
        lblhargaangklung9.setBounds(860, 590, 60, 20);

        lblhargaangklung10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung10.setText("Harga Lama");
        getContentPane().add(lblhargaangklung10);
        lblhargaangklung10.setBounds(160, 380, 60, 20);

        lblhargaangklung11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung11.setText("Harga Lama");
        getContentPane().add(lblhargaangklung11);
        lblhargaangklung11.setBounds(300, 380, 60, 20);

        lblhargaangklung12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung12.setText("Harga Lama");
        getContentPane().add(lblhargaangklung12);
        lblhargaangklung12.setBounds(440, 380, 60, 20);

        lblhargaangklung13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung13.setText("Harga Lama");
        getContentPane().add(lblhargaangklung13);
        lblhargaangklung13.setBounds(580, 380, 60, 20);

        lblhargaangklung14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung14.setText("Harga Lama");
        getContentPane().add(lblhargaangklung14);
        lblhargaangklung14.setBounds(720, 380, 60, 20);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/Mahkota190000.png"))); // NOI18N
        getContentPane().add(jButton22);
        jButton22.setBounds(20, 490, 130, 100);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pangrumatSunda20000.png"))); // NOI18N
        getContentPane().add(jButton23);
        jButton23.setBounds(160, 490, 130, 100);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pangsi80000.png"))); // NOI18N
        getContentPane().add(jButton24);
        jButton24.setBounds(300, 490, 130, 100);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/perangBubat28000.png"))); // NOI18N
        getContentPane().add(jButton25);
        jButton25.setBounds(440, 490, 130, 100);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pisangSale25000.png"))); // NOI18N
        getContentPane().add(jButton26);
        jButton26.setBounds(580, 490, 130, 100);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pustakabasa20000.png"))); // NOI18N
        getContentPane().add(jButton27);
        jButton27.setBounds(720, 490, 130, 100);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/RumahMiniatur60000.png"))); // NOI18N
        getContentPane().add(jButton28);
        jButton28.setBounds(860, 490, 130, 100);

        lblhargamahkota.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargamahkota.setText("Rp. 25.000");
        getContentPane().add(lblhargamahkota);
        lblhargamahkota.setBounds(90, 590, 60, 20);

        lblhargapangrumat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapangrumat.setText("Rp. 25.000");
        getContentPane().add(lblhargapangrumat);
        lblhargapangrumat.setBounds(230, 590, 60, 20);

        lblhargapangsi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapangsi.setText("Rp. 25.000");
        getContentPane().add(lblhargapangsi);
        lblhargapangsi.setBounds(370, 590, 60, 20);

        lblhargaperang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaperang.setText("Rp.25.000");
        getContentPane().add(lblhargaperang);
        lblhargaperang.setBounds(510, 590, 60, 20);

        lblhargapisang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapisang.setText("Rp. 25.000");
        getContentPane().add(lblhargapisang);
        lblhargapisang.setBounds(650, 590, 60, 20);

        lblhargapusaka.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapusaka.setText("Rp. 25.000");
        getContentPane().add(lblhargapusaka);
        lblhargapusaka.setBounds(790, 590, 60, 20);

        lblhargarumah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargarumah.setText("Rp. 25.000");
        getContentPane().add(lblhargarumah);
        lblhargarumah.setBounds(930, 590, 60, 20);

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel82.setText("Rumah");
        getContentPane().add(jLabel82);
        jLabel82.setBounds(860, 460, 49, 30);

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel83.setText("Pusaka");
        getContentPane().add(jLabel83);
        jLabel83.setBounds(720, 460, 100, 30);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setText("Pisang");
        getContentPane().add(jLabel84);
        jLabel84.setBounds(580, 460, 100, 30);

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel85.setText("Perang");
        getContentPane().add(jLabel85);
        jLabel85.setBounds(440, 460, 110, 30);

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel86.setText("Pangsi");
        getContentPane().add(jLabel86);
        jLabel86.setBounds(300, 460, 80, 30);

        jLabel87.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel87.setText("Pangrumat");
        getContentPane().add(jLabel87);
        jLabel87.setBounds(160, 460, 100, 30);

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel88.setText("Mahkota");
        getContentPane().add(jLabel88);
        jLabel88.setBounds(20, 460, 60, 30);

        jmlrumah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlrumah.setText("0");
        getContentPane().add(jmlrumah);
        jmlrumah.setBounds(860, 610, 130, 20);

        jButton43.setText("Ubah");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43);
        jButton43.setBounds(860, 640, 130, 20);

        jButton44.setText("Ubah");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton44);
        jButton44.setBounds(720, 640, 130, 20);

        jmlpusaka.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpusaka.setText("0");
        getContentPane().add(jmlpusaka);
        jmlpusaka.setBounds(720, 610, 130, 20);

        jButton45.setText("Ubah");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton45);
        jButton45.setBounds(580, 640, 130, 20);

        jmlpisang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpisang.setText("0");
        getContentPane().add(jmlpisang);
        jmlpisang.setBounds(580, 610, 130, 20);

        jButton46.setText("Ubah");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton46);
        jButton46.setBounds(440, 640, 130, 20);

        jmlperang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlperang.setText("0");
        getContentPane().add(jmlperang);
        jmlperang.setBounds(440, 610, 130, 20);

        jButton47.setText("Ubah");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton47);
        jButton47.setBounds(300, 640, 130, 20);

        jmlpangsi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpangsi.setText("0");
        getContentPane().add(jmlpangsi);
        jmlpangsi.setBounds(300, 610, 130, 20);

        jButton48.setText("Ubah");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton48);
        jButton48.setBounds(160, 640, 120, 20);

        jmlpangrumat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpangrumat.setText("0");
        getContentPane().add(jmlpangrumat);
        jmlpangrumat.setBounds(160, 610, 120, 20);

        jButton49.setText("Ubah");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton49);
        jButton49.setBounds(20, 640, 130, 20);

        jmlmahkota.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlmahkota.setText("0");
        getContentPane().add(jmlmahkota);
        jmlmahkota.setBounds(20, 610, 130, 20);

        lblhargaangklung15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung15.setText("Harga Lama");
        getContentPane().add(lblhargaangklung15);
        lblhargaangklung15.setBounds(20, 380, 60, 20);

        lblhargaangklung16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung16.setText("Harga Lama");
        getContentPane().add(lblhargaangklung16);
        lblhargaangklung16.setBounds(860, 800, 60, 20);

        lblhargaangklung17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung17.setText("Harga Lama");
        getContentPane().add(lblhargaangklung17);
        lblhargaangklung17.setBounds(160, 590, 60, 20);

        lblhargaangklung18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung18.setText("Harga Lama");
        getContentPane().add(lblhargaangklung18);
        lblhargaangklung18.setBounds(300, 590, 60, 20);

        lblhargaangklung19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung19.setText("Harga Lama");
        getContentPane().add(lblhargaangklung19);
        lblhargaangklung19.setBounds(440, 590, 60, 20);

        lblhargaangklung20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung20.setText("Harga Lama");
        getContentPane().add(lblhargaangklung20);
        lblhargaangklung20.setBounds(580, 590, 60, 20);

        lblhargaangklung21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung21.setText("Harga Lama");
        getContentPane().add(lblhargaangklung21);
        lblhargaangklung21.setBounds(720, 590, 60, 20);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/sasakalaSunda17000.png"))); // NOI18N
        getContentPane().add(jButton50);
        jButton50.setBounds(20, 700, 130, 100);

        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/SigerAnak55000.png"))); // NOI18N
        getContentPane().add(jButton51);
        jButton51.setBounds(160, 700, 130, 100);

        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/SimpayBasaSunda98000.png"))); // NOI18N
        getContentPane().add(jButton52);
        jButton52.setBounds(300, 700, 130, 100);

        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/suling10000.png"))); // NOI18N
        getContentPane().add(jButton53);
        jButton53.setBounds(440, 700, 130, 100);

        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/tales15000.png"))); // NOI18N
        getContentPane().add(jButton54);
        jButton54.setBounds(580, 700, 130, 100);

        jButton55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/totopong12000.png"))); // NOI18N
        getContentPane().add(jButton55);
        jButton55.setBounds(720, 700, 130, 100);

        jButton56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/udeng75000.png"))); // NOI18N
        getContentPane().add(jButton56);
        jButton56.setBounds(860, 700, 130, 100);

        lblhargasasakala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasasakala.setText("Rp. 25.000");
        getContentPane().add(lblhargasasakala);
        lblhargasasakala.setBounds(90, 800, 60, 20);

        lblhargasiger.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasiger.setText("Rp. 25.000");
        getContentPane().add(lblhargasiger);
        lblhargasiger.setBounds(230, 800, 60, 20);

        lblhargasimpay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasimpay.setText("Rp. 25.000");
        getContentPane().add(lblhargasimpay);
        lblhargasimpay.setBounds(370, 800, 60, 20);

        lblhargasuling.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasuling.setText("Rp. 25.000");
        getContentPane().add(lblhargasuling);
        lblhargasuling.setBounds(510, 800, 60, 20);

        lblhargatales.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargatales.setText("Rp. 25.000");
        getContentPane().add(lblhargatales);
        lblhargatales.setBounds(650, 800, 60, 20);

        lblhargatotopong.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargatotopong.setText("Rp. 25.000");
        getContentPane().add(lblhargatotopong);
        lblhargatotopong.setBounds(790, 800, 60, 20);

        lblhargaudeng.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaudeng.setText("Rp. 25.000");
        getContentPane().add(lblhargaudeng);
        lblhargaudeng.setBounds(930, 800, 60, 20);

        jLabel110.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel110.setText("Udeng");
        getContentPane().add(jLabel110);
        jLabel110.setBounds(860, 670, 130, 30);

        jLabel111.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel111.setText("Totopong");
        getContentPane().add(jLabel111);
        jLabel111.setBounds(720, 670, 70, 30);

        jLabel112.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel112.setText("Tales");
        getContentPane().add(jLabel112);
        jLabel112.setBounds(580, 670, 110, 30);

        jLabel113.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel113.setText("Suling");
        getContentPane().add(jLabel113);
        jLabel113.setBounds(440, 670, 80, 30);

        jLabel114.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel114.setText("Simpay");
        getContentPane().add(jLabel114);
        jLabel114.setBounds(300, 670, 150, 30);

        jLabel115.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel115.setText("Siger");
        getContentPane().add(jLabel115);
        jLabel115.setBounds(160, 670, 50, 30);

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel116.setText("Sasakala");
        getContentPane().add(jLabel116);
        jLabel116.setBounds(20, 670, 110, 30);

        jmludeng.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmludeng.setText("0");
        getContentPane().add(jmludeng);
        jmludeng.setBounds(860, 820, 130, 20);

        jButton57.setText("Ubah");
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton57);
        jButton57.setBounds(860, 850, 130, 20);

        jButton58.setText("Ubah");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton58);
        jButton58.setBounds(720, 850, 130, 20);

        jmltotopong.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmltotopong.setText("0");
        getContentPane().add(jmltotopong);
        jmltotopong.setBounds(720, 820, 130, 20);

        jButton59.setText("Ubah");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton59);
        jButton59.setBounds(580, 850, 130, 20);

        jmltales.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmltales.setText("0");
        getContentPane().add(jmltales);
        jmltales.setBounds(580, 820, 130, 20);

        jButton60.setText("Ubah");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton60);
        jButton60.setBounds(440, 850, 130, 20);

        jmlsuling.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsuling.setText("0");
        getContentPane().add(jmlsuling);
        jmlsuling.setBounds(440, 820, 130, 20);

        jButton61.setText("Ubah");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton61);
        jButton61.setBounds(300, 850, 130, 20);

        jmlsimpay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsimpay.setText("0");
        getContentPane().add(jmlsimpay);
        jmlsimpay.setBounds(300, 820, 130, 20);

        jButton62.setText("Ubah");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton62);
        jButton62.setBounds(160, 850, 130, 20);

        jmlsiger.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsiger.setText("0");
        getContentPane().add(jmlsiger);
        jmlsiger.setBounds(160, 820, 130, 20);

        jButton63.setText("Ubah");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton63);
        jButton63.setBounds(20, 850, 130, 20);

        jmlsasakala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsasakala.setText("0");
        getContentPane().add(jmlsasakala);
        jmlsasakala.setBounds(20, 820, 130, 20);

        lblhargaangklung22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung22.setText("Harga Lama");
        getContentPane().add(lblhargaangklung22);
        lblhargaangklung22.setBounds(20, 590, 60, 20);

        lblhargaangklung23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung23.setText("Harga Lama");
        getContentPane().add(lblhargaangklung23);
        lblhargaangklung23.setBounds(20, 800, 60, 20);

        lblhargaangklung24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung24.setText("Harga Lama");
        getContentPane().add(lblhargaangklung24);
        lblhargaangklung24.setBounds(160, 800, 60, 20);

        lblhargaangklung25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung25.setText("Harga Lama");
        getContentPane().add(lblhargaangklung25);
        lblhargaangklung25.setBounds(300, 800, 60, 20);

        lblhargaangklung26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung26.setText("Harga Lama");
        getContentPane().add(lblhargaangklung26);
        lblhargaangklung26.setBounds(440, 800, 60, 20);

        lblhargaangklung27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung27.setText("Harga Lama");
        getContentPane().add(lblhargaangklung27);
        lblhargaangklung27.setBounds(580, 800, 60, 20);

        lblhargaangklung28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung28.setText("Harga Lama");
        getContentPane().add(lblhargaangklung28);
        lblhargaangklung28.setBounds(720, 800, 60, 20);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 10, 90, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlangklung.getText())>0){
            obj.setHargaAngklung(Integer.parseInt(jmlangklung.getText()));
            lblhargaangklung.setText("Rp. " + obj.getHargaAngklung());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       this.setVisible(false);
       new adminHome().setVisible(true); 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlbesokap.getText())>0){
            obj.setHargaBesokap(Integer.parseInt(jmlbesokap.getText()));
            lblhargabesokap.setText("Rp. " + obj.getHargaBesokap());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
          produk obj = new produk();
        try{
          if(Integer.parseInt(jmlblankon.getText())>0){
            obj.setHargaBlankon(Integer.parseInt(jmlblankon.getText()));
            lblhargablankon.setText("Rp. " + obj.getHargaBlankon());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlbros.getText())>0){
            obj.setHargaBros(Integer.parseInt(jmlbros.getText()));
            lblhargabros.setText("Rp. " + obj.getHargaBros());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
       produk obj = new produk();
        try{
          if(Integer.parseInt(jmlbukubelajar.getText())>0){
            obj.setHargaBukuBelajar(Integer.parseInt(jmlbukubelajar.getText()));
            lblhargabukubelajar.setText("Rp. " + obj.getHargaBukuBelajar());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlbukucerita.getText())>0){
            obj.setHargaBukuCerita(Integer.parseInt(jmlbukucerita.getText()));
            lblhargabukucerita.setText("Rp. " + obj.getHargaBukuCerita());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlbumbu.getText())>0){
            obj.setHargaBumbu(Integer.parseInt(jmlbumbu.getText()));
            lblhargabumbu.setText("Rp. " + obj.getHargaBumbu());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlcelengan.getText())>0){
            obj.setHargaCelengan(Integer.parseInt(jmlcelengan.getText()));
            lblhargacelengan.setText("Rp. " + obj.getHargaCelengan());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
       produk obj = new produk();
        try{
          if(Integer.parseInt(jmliket.getText())>0){
            obj.setHargaIket(Integer.parseInt(jmliket.getText()));
            lblhargaiket.setText("Rp. " + obj.getHargaIket());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
       
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlkamus.getText())>0){
            obj.setHargaKamus(Integer.parseInt(jmlkamus.getText()));
            lblhargakamus.setText("Rp. " + obj.getHargaKamus());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
        
       
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
      
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlkaos.getText())>0){
            obj.setHargaKaos(Integer.parseInt(jmlkaos.getText()));
            lblhargakaos.setText("Rp. " + obj.getHargaKaos());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
           produk obj = new produk();
        try{
          if(Integer.parseInt(jmlkecapi.getText())>0){
            obj.setHargaKecapi(Integer.parseInt(jmlkecapi.getText()));
            lblhargakecapi.setText("Rp. " + obj.getHargaKecapi());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlkopi.getText())>0){
            obj.setHargaKopi(Integer.parseInt(jmlkopi.getText()));
            lblhargakopi.setText("Rp. " + obj.getHargaKopi());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlliwet.getText())>0){
            obj.setHargaLiwet(Integer.parseInt(jmlliwet.getText()));
            lblhargaliwet.setText("Rp. " + obj.getHargaLiwet());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlmahkota.getText())>0){
            obj.setHargaMahkota(Integer.parseInt(jmlmahkota.getText()));
            lblhargamahkota.setText("Rp. " + obj.getHargaMahkota());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
       produk obj = new produk();
        try{
          if(Integer.parseInt(jmlpangrumat.getText())>0){
            obj.setHargaPangrumat(Integer.parseInt(jmlpangrumat.getText()));
            lblhargapangrumat.setText("Rp. " + obj.getHargaPangrumat());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlpangsi.getText())>0){
            obj.setHargaPangsi(Integer.parseInt(jmlpangsi.getText()));
            lblhargapangsi.setText("Rp. " + obj.getHargaPangsi());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlperang.getText())>0){
            obj.setHargaPerang(Integer.parseInt(jmlperang.getText()));
            lblhargaperang.setText("Rp. " + obj.getHargaPerang());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
       produk obj = new produk();
        try{
          if(Integer.parseInt(jmlpisang.getText())>0){
            obj.setHargaPisang(Integer.parseInt(jmlpisang.getText()));
            lblhargapisang.setText("Rp. " + obj.getHargaPisang());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
      produk obj = new produk();
        try{
          if(Integer.parseInt(jmlpisang.getText())>0){
            obj.setHargaPustaka(Integer.parseInt(jmlpusaka.getText()));
            lblhargapusaka.setText("Rp. " + obj.getHargaPustaka());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlrumah.getText())>0){
            obj.setHargaRumah(Integer.parseInt(jmlrumah.getText()));
            lblhargarumah.setText("Rp. " + obj.getHargaRumah());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
       produk obj = new produk();
        try{
          if(Integer.parseInt(jmlsasakala.getText())>0){
            obj.setHargaSasakala(Integer.parseInt(jmlsasakala.getText()));
            lblhargasasakala.setText("Rp. " + obj.getHargaSasakala());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        produk obj = new produk();
        try{
          if(Integer.parseInt(jmlsiger.getText())>0){
            obj.setHargaSiger(Integer.parseInt(jmlsiger.getText()));
            lblhargasiger.setText("Rp. " + obj.getHargaSiger());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
         // TODO add your handling code here:
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlsimpay.getText())>0){
            obj.setHargaSimpay(Integer.parseInt(jmlsimpay.getText()));
            lblhargasimpay.setText("Rp. " + obj.getHargaSimpay());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
          // TODO add your handling code here:
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmlsuling.getText())>0){
            obj.setHargaSuling(Integer.parseInt(jmlsuling.getText()));
            lblhargasuling.setText("Rp. " + obj.getHargaSuling());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmltales.getText())>0){
            obj.setHargaTales(Integer.parseInt(jmltales.getText()));
            lblhargatales.setText("Rp. " + obj.getHargaTales());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmltotopong.getText())>0){
            obj.setHargaTotopong(Integer.parseInt(jmltotopong.getText()));
            lblhargatotopong.setText("Rp. " + obj.getHargaTotopong());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
          // TODO add your handling code here:
         produk obj = new produk();
        try{
          if(Integer.parseInt(jmludeng.getText())>0){
            obj.setHargaUdeng(Integer.parseInt(jmludeng.getText()));
            lblhargaudeng.setText("Rp. " + obj.getHargaUdeng());
            alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
               alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
         }  
        }
        catch(NumberFormatException e){
             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jmlangklungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlangklungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlangklungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahHargaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahHargaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahHargaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahHargaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahHargaProdukFrame().setVisible(true);
            }
        });
    }
    public void setHarga(){
        produk obj = new produk();
        lblhargaangklung.setText("Rp. " + obj.getHargaAngklung());
        lblhargabesokap.setText("Rp. " + obj.getHargaBesokap());
        lblhargablankon.setText("Rp. " + obj.getHargaBlankon());
        lblhargabros.setText("Rp. "+ obj.getHargaBros());
        lblhargabukubelajar.setText("Rp. " + obj.getHargaBukuBelajar());
        lblhargabukucerita.setText("Rp. " + obj.getHargaBukuCerita());
        lblhargabumbu.setText("Rp. " + obj.getHargaBumbu());
        lblhargacelengan.setText("Rp. " + obj.getHargaCelengan());
        lblhargaiket.setText("Rp. " +obj.getHargaIket());
        lblhargakamus.setText("Rp. "+ obj.getHargaKamus());
        lblhargakaos.setText("Rp. " + obj.getHargaKaos());
        lblhargakecapi.setText("Rp. " + obj.getHargaKecapi());
        lblhargakopi.setText("Rp. " + obj.getHargaKopi());
        lblhargaliwet.setText("Rp. " + obj.getHargaLiwet());
        lblhargamahkota.setText("Rp. " + obj.getHargaMahkota());
        lblhargapangrumat.setText("Rp. " + obj.getHargaPangrumat());
        lblhargapangsi.setText("Rp. " + obj.getHargaPangsi());
        lblhargaperang.setText("Rp. " + obj.getHargaPerang());
        lblhargapisang.setText("Rp. " + obj.getHargaPisang());
        lblhargapusaka.setText("Rp. " + obj.getHargaPustaka());
        lblhargarumah.setText("Rp. "+ obj.getHargaRumah());
        lblhargasasakala.setText("Rp. " +obj.getHargaSasakala());
        lblhargasiger.setText("Rp. " + obj.getHargaSiger());
        lblhargasimpay.setText("Rp. " + obj.getHargaSimpay());
        lblhargasuling.setText("Rp. " + obj.getHargaSuling());
        lblhargatales.setText("Rp. " + obj.getHargaTales());
        lblhargatotopong.setText("Rp. " + obj.getHargaTotopong());
        lblhargaudeng.setText("Rp. " + obj.getHargaUdeng());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JTextField jmlangklung;
    private javax.swing.JTextField jmlbesokap;
    private javax.swing.JTextField jmlblankon;
    private javax.swing.JTextField jmlbros;
    private javax.swing.JTextField jmlbukubelajar;
    private javax.swing.JTextField jmlbukucerita;
    private javax.swing.JTextField jmlbumbu;
    private javax.swing.JTextField jmlcelengan;
    private javax.swing.JTextField jmliket;
    private javax.swing.JTextField jmlkamus;
    private javax.swing.JTextField jmlkaos;
    private javax.swing.JTextField jmlkecapi;
    private javax.swing.JTextField jmlkopi;
    private javax.swing.JTextField jmlliwet;
    private javax.swing.JTextField jmlmahkota;
    private javax.swing.JTextField jmlpangrumat;
    private javax.swing.JTextField jmlpangsi;
    private javax.swing.JTextField jmlperang;
    private javax.swing.JTextField jmlpisang;
    private javax.swing.JTextField jmlpusaka;
    private javax.swing.JTextField jmlrumah;
    private javax.swing.JTextField jmlsasakala;
    private javax.swing.JTextField jmlsiger;
    private javax.swing.JTextField jmlsimpay;
    private javax.swing.JTextField jmlsuling;
    private javax.swing.JTextField jmltales;
    private javax.swing.JTextField jmltotopong;
    private javax.swing.JTextField jmludeng;
    private javax.swing.JLabel lblhargaangklung;
    private javax.swing.JLabel lblhargaangklung10;
    private javax.swing.JLabel lblhargaangklung11;
    private javax.swing.JLabel lblhargaangklung12;
    private javax.swing.JLabel lblhargaangklung13;
    private javax.swing.JLabel lblhargaangklung14;
    private javax.swing.JLabel lblhargaangklung15;
    private javax.swing.JLabel lblhargaangklung16;
    private javax.swing.JLabel lblhargaangklung17;
    private javax.swing.JLabel lblhargaangklung18;
    private javax.swing.JLabel lblhargaangklung19;
    private javax.swing.JLabel lblhargaangklung2;
    private javax.swing.JLabel lblhargaangklung20;
    private javax.swing.JLabel lblhargaangklung21;
    private javax.swing.JLabel lblhargaangklung22;
    private javax.swing.JLabel lblhargaangklung222;
    private javax.swing.JLabel lblhargaangklung23;
    private javax.swing.JLabel lblhargaangklung24;
    private javax.swing.JLabel lblhargaangklung25;
    private javax.swing.JLabel lblhargaangklung26;
    private javax.swing.JLabel lblhargaangklung27;
    private javax.swing.JLabel lblhargaangklung28;
    private javax.swing.JLabel lblhargaangklung3;
    private javax.swing.JLabel lblhargaangklung4;
    private javax.swing.JLabel lblhargaangklung5;
    private javax.swing.JLabel lblhargaangklung6;
    private javax.swing.JLabel lblhargaangklung7;
    private javax.swing.JLabel lblhargaangklung8;
    private javax.swing.JLabel lblhargaangklung9;
    private javax.swing.JLabel lblhargabesokap;
    private javax.swing.JLabel lblhargablankon;
    private javax.swing.JLabel lblhargabros;
    private javax.swing.JLabel lblhargabukubelajar;
    private javax.swing.JLabel lblhargabukucerita;
    private javax.swing.JLabel lblhargabumbu;
    private javax.swing.JLabel lblhargacelengan;
    private javax.swing.JLabel lblhargaiket;
    private javax.swing.JLabel lblhargakamus;
    private javax.swing.JLabel lblhargakaos;
    private javax.swing.JLabel lblhargakecapi;
    private javax.swing.JLabel lblhargakopi;
    private javax.swing.JLabel lblhargaliwet;
    private javax.swing.JLabel lblhargamahkota;
    private javax.swing.JLabel lblhargapangrumat;
    private javax.swing.JLabel lblhargapangsi;
    private javax.swing.JLabel lblhargaperang;
    private javax.swing.JLabel lblhargapisang;
    private javax.swing.JLabel lblhargapusaka;
    private javax.swing.JLabel lblhargarumah;
    private javax.swing.JLabel lblhargasasakala;
    private javax.swing.JLabel lblhargasiger;
    private javax.swing.JLabel lblhargasimpay;
    private javax.swing.JLabel lblhargasuling;
    private javax.swing.JLabel lblhargatales;
    private javax.swing.JLabel lblhargatotopong;
    private javax.swing.JLabel lblhargaudeng;
    // End of variables declaration//GEN-END:variables
}
