/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laporan;

import java.util.ArrayList;
import java.util.Arrays;
import meuli.distributor.customer.customerA;
import meuli.distributor.customer.customerB;
import meuli.distributor.customer.customerC;
import meuli.distributor.customer.customerD;
import meuli.distributor.customer.customerE;
import meuli.distributor.distributorframe;

/**
 *
 * @author thero
 */
public class pembelianFrameTestCustomer extends javax.swing.JFrame {
public static String transaksi;
public static String stok;
public static ArrayList<String> listBarangDistributorA = new ArrayList<String>();
public static ArrayList<String> listTampungDistributorA = new ArrayList<String>();
    /**
     * Creates new form pembelianFrame
     */
    public pembelianFrameTestCustomer() {
        initComponents();
        txtTotalPengeluaran.setEditable(false);
        
       
      //  comboDistA.setModel(new DefaultComboBoxModel(ls.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert1 = new javax.swing.JOptionPane();
        txtTotalPengeluaran = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        comboDist = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        distributorname = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtkonfirm = new javax.swing.JTextArea();
        txtJumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1153, 825));
        getContentPane().setLayout(null);

        txtTotalPengeluaran.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txtTotalPengeluaran);
        txtTotalPengeluaran.setBounds(480, 100, 450, 60);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 100, 40);

        comboDist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(comboDist);
        comboDist.setBounds(40, 280, 230, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Transaksi Ke-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 240, 150, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 350, 230, 40);

        distributorname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        distributorname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUSTOMER A", "CUSTOMER B", "CUSTOMER C", "CUSTOMER D", "CUSTOMER E" }));
        getContentPane().add(distributorname);
        distributorname.setBounds(40, 190, 230, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("JUMLAH TRANSAKSI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 620, 420, 60);

        txtkonfirm.setColumns(20);
        txtkonfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonfirm.setRows(5);
        txtkonfirm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(txtkonfirm);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(480, 180, 450, 420);

        txtJumlah.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txtJumlah);
        txtJumlah.setBounds(480, 620, 450, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("TOTAL PENGELUARAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 100, 420, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new semualaporanFame().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
       transaksi = "";
       txtkonfirm.setText("");
      
       
       String distributor = distributorname.getSelectedItem().toString();
       String indexText = comboDist.getSelectedItem().toString();
       //alert1.showMessageDialog(null, indexText , "Berhasil!", alert1.INFORMATION_MESSAGE);
       int indexa = Integer.parseInt(indexText);    


    
       if(distributor.equals("CUSTOMER A")){
            customerA obj = new customerA();
           transaksi = String.join("\n", obj.listTransaksi.get(indexa-1));
        
        txtTotalPengeluaran.setText(Integer.toString(obj.totalHarga));
        txtJumlah.setText(Integer.toString(obj.jmltransaksi));
       }
       else if (distributor.equals("CUSTOMER B")){
            customerB obj = new customerB();
          transaksi = String.join("\n", obj.listTransaksi.get(indexa-1));
           txtJumlah.setText(Integer.toString(obj.jmltransaksi));
        
        txtTotalPengeluaran.setText(Integer.toString(obj.totalHarga));
       }
       else if (distributor.equals("CUSTOMER C")){
            customerC obj = new customerC();
         transaksi = String.join("\n", obj.listTransaksi.get(indexa-1));
          txtJumlah.setText(Integer.toString(obj.jmltransaksi));
        
        txtTotalPengeluaran.setText(Integer.toString(obj.totalHarga));
       }
       else if (distributor.equals("CUSTOMER D")){
            customerD obj = new customerD();
         transaksi = String.join("\n", obj.listTransaksi.get(indexa-1));
         txtJumlah.setText(Integer.toString(obj.jmltransaksi));
        txtTotalPengeluaran.setText(Integer.toString(obj.totalHarga));
       }
       else if (distributor.equals("CUSTOMER E")){
            customerE obj = new customerE();
         transaksi = String.join("\n", obj.listTransaksi.get(indexa-1));
         txtJumlah.setText(Integer.toString(obj.jmltransaksi));
        txtTotalPengeluaran.setText(Integer.toString(obj.totalHarga));
       }
       
     //  alert1.showMessageDialog(null, Arrays.toString(obj.listPembelianDistributorA.toArray()) , "Berhasil!", alert1.INFORMATION_MESSAGE);
       txtkonfirm.append(transaksi);
       

        
      }
        catch(IndexOutOfBoundsException e){
               alert1.showMessageDialog(null, "Tidak ada Index!" , "PERHATIAN!", alert1.INFORMATION_MESSAGE);
          
               }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembelianFrameTestCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembelianFrameTestCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembelianFrameTestCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembelianFrameTestCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembelianFrameTestCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JComboBox<String> comboDist;
    private javax.swing.JComboBox<String> distributorname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTotalPengeluaran;
    private javax.swing.JTextArea txtkonfirm;
    // End of variables declaration//GEN-END:variables
}
