/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laporan;

import java.util.ArrayList;
import java.util.Arrays;
import meuli.distributor.distributorframe;

/**
 *
 * @author thero
 */
public class pembelianFrame extends javax.swing.JFrame {
public static String transaksi;
public static String stok;
public static ArrayList<String> listBarangDistributorA = new ArrayList<String>();
public static ArrayList<String> listTampungDistributorA = new ArrayList<String>();
    /**
     * Creates new form pembelianFrame
     */
    public pembelianFrame() {
        initComponents();
        txtTotalPengeluaran.setEditable(false);
        pembelian obj = new pembelian();
        txtTotalPengeluaran.setText(Integer.toString(obj.getTotalPengeluaran()));
       
      //  comboDistA.setModel(new DefaultComboBoxModel(ls.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert1 = new javax.swing.JOptionPane();
        txtTotalPengeluaran = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        comboDist = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        distributorname = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtkonfirm = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1153, 825));
        getContentPane().setLayout(null);

        txtTotalPengeluaran.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txtTotalPengeluaran);
        txtTotalPengeluaran.setBounds(480, 100, 450, 60);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 100, 40);

        comboDist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(comboDist);
        comboDist.setBounds(40, 280, 230, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Transaksi Ke-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 240, 150, 40);

        txtDetail.setColumns(20);
        txtDetail.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtDetail.setRows(5);
        txtDetail.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(txtDetail);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(780, 190, 310, 420);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 350, 230, 40);

        distributorname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        distributorname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISTRIBUTOR A", "DISTRIBUTOR B", "DISTRIBUTOR C", "DISTRIBUTOR D" }));
        getContentPane().add(distributorname);
        distributorname.setBounds(40, 190, 230, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("TOTAL PENGELUARAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 420, 60);

        txtkonfirm.setColumns(20);
        txtkonfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonfirm.setRows(5);
        txtkonfirm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(txtkonfirm);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 190, 450, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new semualaporanFame().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
           transaksi = "";
           txtkonfirm.setText("");
           transaksi = "";
           txtDetail.setText("");
       pembelian obj = new pembelian();
       obj.listRecordBarangDistributorA.clear();
       String distributor = distributorname.getSelectedItem().toString();
       String indexText = comboDist.getSelectedItem().toString();
       //alert1.showMessageDialog(null, indexText , "Berhasil!", alert1.INFORMATION_MESSAGE);
       int indexa = Integer.parseInt(indexText);    
        listBarangDistributorA.add(" \t\t Meuli Point of Sale"
            + "\n\t\t Product Summary"
            + "\n============================"
            + "\nJumlah\t\t Nama Barang");

    
    
       if(distributor.equals("DISTRIBUTOR A")){
           transaksi = String.join("\n", obj.listPembelianDistributorA.get(indexa-1));
       }
       else if (distributor.equals("DISTRIBUTOR B")){
           transaksi = String.join("\n", obj.listPembelianDistributorB.get(indexa-1));
       }
       else if (distributor.equals("DISTRIBUTOR C")){
           transaksi = String.join("\n", obj.listPembelianDistributorC.get(indexa-1));
       }
       else if (distributor.equals("DISTRIBUTOR D")){
           transaksi = String.join("\n", obj.listPembelianDistributorD.get(indexa-1));
       }
     //  alert1.showMessageDialog(null, Arrays.toString(obj.listPembelianDistributorA.toArray()) , "Berhasil!", alert1.INFORMATION_MESSAGE);
       txtkonfirm.append(transaksi);
       
             
        obj.listRecordBarangDistributorA.add(""
            + "         Meuli Point of Sale"
            + "\n       Total Pemesanan Barang"
            + "\n====================================="
            + "\nJumlah\t\t     Nama Barang");
      
     
        
       if(distributor.equals("DISTRIBUTOR A")){
         if(obj.recordAngklung> 0){ 
         obj.listRecordBarangDistributorA.add(obj.recordAngklung +"\t\t     Angklung");
    }
    if(obj.recordBesokap> 0){
          obj.listRecordBarangDistributorA.add(obj.recordBesokap +"\t\t     Besokap");
    }
    if(obj.recordBlankon> 0){
         obj.listRecordBarangDistributorA.add(obj.recordBlankon +"\t\t     Blankon");
    }
    if(obj.recordBros> 0){
        obj.listRecordBarangDistributorA.add(obj.recordBros +"\t\t     Bros");
    }
    if(obj.recordBukuBelajar> 0){
        obj.listRecordBarangDistributorA.add(obj.recordBukuBelajar +"\t\t     Buku Belajar");
    }
    if(obj.recordBukuCerita> 0){    
         obj.listRecordBarangDistributorA.add(obj.recordBukuCerita +"\t\t     Buku Cerita");
    }
    if(obj.recordBumbu> 0){     
         obj.listRecordBarangDistributorA.add(obj.recordBumbu +"\t\t     Bumbu");
    }
           stok = String.join("\n", obj.listRecordBarangDistributorA);
           
       }
 //celengan,iket,kamus,kaos,kecapi,kopi,liwet     
       if(distributor.equals("DISTRIBUTOR B")){
         if(obj.recordCelengan> 0){ 
         obj.listRecordBarangDistributorA.add(obj.recordCelengan +"\t\t     Angklung");
    }
    if(obj.recordIket> 0){
          obj.listRecordBarangDistributorA.add(obj.recordIket +"\t\t     Besokap");
    }
    if(obj.recordKamus> 0){
         obj.listRecordBarangDistributorA.add(obj.recordKamus +"\t\t     Blankon");
    }
    if(obj.recordKaos> 0){
        obj.listRecordBarangDistributorA.add(obj.recordKaos +"\t\t     Bros");
    }
    if(obj.recordKecapi> 0){
        obj.listRecordBarangDistributorA.add(obj.recordKopi +"\t\t     Buku Belajar");
    }
    if(obj.recordLiwet> 0){    
         obj.listRecordBarangDistributorA.add(obj.recordLiwet +"\t\t     Buku Cerita");
    }
    if(obj.recordBumbu> 0){     
         obj.listRecordBarangDistributorA.add(obj.recordBumbu +"\t\t     Bumbu");
    }
           stok = String.join("\n", obj.listRecordBarangDistributorA);
           
       }
         
         
        txtDetail.append(stok);
        
      }
        catch(IndexOutOfBoundsException e){
               alert1.showMessageDialog(null, "Tidak ada Index!" , "PERHATIAN!", alert1.INFORMATION_MESSAGE);
          
               }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembelianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembelianFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JComboBox<String> comboDist;
    private javax.swing.JComboBox<String> distributorname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextField txtTotalPengeluaran;
    private javax.swing.JTextArea txtkonfirm;
    // End of variables declaration//GEN-END:variables
}
