/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import laporan.dashboard;
import laporan.pembelian;
import manageproduk.produk;
import meuli.distributor.distributorA;
/**
 *
 * @author thero
 */
public class distributorAFrame extends javax.swing.JFrame {
    
  public ArrayList<String> listTransaksi = new ArrayList<String>();
    private int harga = 0;
    public static String transaksi;
    /**
     * Creates new form distributorAFrame
     */
    public distributorAFrame() {
       initComponents();
       distributorA distA = new distributorA();
      setHarga();
      mulaiTransaksi();
      jButton12.setEnabled(false);
       
    }
    
    public void totalHarga(int x){
        harga+=x;
    }
    public int getTotalHarga(){
        return harga;
    }
    
    public void resetHarga(){
        harga = 0;
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lblhargabukubelajar = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        lblhargabukucerita = new javax.swing.JLabel();
        lblstockbukucerita = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        lblstockbumbu = new javax.swing.JLabel();
        lblhargabumbu = new javax.swing.JLabel();
        lblstockbukubelajar = new javax.swing.JLabel();
        lblstockbros = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jmlbesokap = new javax.swing.JTextField();
        jmlblankon = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jmlbros = new javax.swing.JTextField();
        jmlbukubelajar = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        jmlbukucerita = new javax.swing.JTextField();
        jButton34 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jmlbumbu = new javax.swing.JTextField();
        jButton35 = new javax.swing.JButton();
        jmlangklung = new javax.swing.JTextField();
        lblhargabros = new javax.swing.JLabel();
        lblstockblankon = new javax.swing.JLabel();
        lblhargablankon = new javax.swing.JLabel();
        lblstockbesokap = new javax.swing.JLabel();
        lblhargabesokap = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblstockangklung = new javax.swing.JLabel();
        lblhargaangklung = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        alert1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtkonfirm = new javax.swing.JTextArea();
        txtTotalHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/broskujang50000.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 140, 130, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/angklung25000.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 140, 130, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/beskap115000.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 140, 130, 100);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/blankonSunda90000.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 140, 130, 100);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bukubelajar25000.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(590, 140, 130, 100);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Buku Belajar");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(590, 110, 110, 30);

        lblhargabukubelajar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabukubelajar.setText("Rp. 25.000");
        getContentPane().add(lblhargabukubelajar);
        lblhargabukubelajar.setBounds(670, 240, 60, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bukucerita25000.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(730, 140, 130, 100);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Buku Cerita");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(730, 110, 110, 30);

        lblhargabukucerita.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabukucerita.setText("Rp. 25.000");
        getContentPane().add(lblhargabukucerita);
        lblhargabukucerita.setBounds(810, 240, 60, 20);

        lblstockbukucerita.setText("5");
        getContentPane().add(lblstockbukucerita);
        lblstockbukucerita.setBounds(850, 120, 10, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Bumbu");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(870, 110, 100, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bumbuNasgor30000.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(870, 140, 130, 100);

        lblstockbumbu.setText("5");
        getContentPane().add(lblstockbumbu);
        lblstockbumbu.setBounds(990, 120, 10, 20);

        lblhargabumbu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabumbu.setText("Rp. 25.000");
        getContentPane().add(lblhargabumbu);
        lblhargabumbu.setBounds(950, 240, 60, 20);

        lblstockbukubelajar.setText("5");
        getContentPane().add(lblstockbukubelajar);
        lblstockbukubelajar.setBounds(710, 120, 10, 20);

        lblstockbros.setText("5");
        getContentPane().add(lblstockbros);
        lblstockbros.setBounds(560, 120, 10, 20);

        jButton29.setText("-");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(30, 240, 37, 20);

        jmlbesokap.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbesokap.setText("0");
        getContentPane().add(jmlbesokap);
        jmlbesokap.setBounds(210, 240, 30, 20);

        jmlblankon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlblankon.setText("0");
        getContentPane().add(jmlblankon);
        jmlblankon.setBounds(350, 240, 30, 20);

        jButton31.setText("-");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(310, 240, 37, 20);

        jButton30.setText("-");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(170, 240, 37, 20);

        jmlbros.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbros.setText("0");
        getContentPane().add(jmlbros);
        jmlbros.setBounds(490, 240, 30, 20);

        jmlbukubelajar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbukubelajar.setText("0");
        getContentPane().add(jmlbukubelajar);
        jmlbukubelajar.setBounds(630, 240, 30, 20);

        jButton33.setText("-");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(590, 240, 37, 20);

        jmlbukucerita.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbukucerita.setText("0");
        getContentPane().add(jmlbukucerita);
        jmlbukucerita.setBounds(770, 240, 30, 20);

        jButton34.setText("-");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(730, 240, 37, 20);

        jButton32.setText("-");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(450, 240, 37, 20);

        jmlbumbu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbumbu.setText("0");
        getContentPane().add(jmlbumbu);
        jmlbumbu.setBounds(910, 240, 30, 20);

        jButton35.setText("-");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(870, 240, 37, 20);

        jmlangklung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlangklung.setText("0");
        getContentPane().add(jmlangklung);
        jmlangklung.setBounds(70, 240, 30, 20);

        lblhargabros.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabros.setText("Rp. 25.000");
        getContentPane().add(lblhargabros);
        lblhargabros.setBounds(530, 240, 60, 20);

        lblstockblankon.setText("5");
        getContentPane().add(lblstockblankon);
        lblstockblankon.setBounds(420, 120, 10, 20);

        lblhargablankon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargablankon.setText("Rp. 25.000");
        getContentPane().add(lblhargablankon);
        lblhargablankon.setBounds(390, 240, 60, 20);

        lblstockbesokap.setText("5");
        getContentPane().add(lblstockbesokap);
        lblstockbesokap.setBounds(280, 120, 10, 20);

        lblhargabesokap.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargabesokap.setText("Rp. 25.000");
        getContentPane().add(lblhargabesokap);
        lblhargabesokap.setBounds(250, 240, 50, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bros");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 110, 50, 30);

        lblstockangklung.setText("10");
        getContentPane().add(lblstockangklung);
        lblstockangklung.setBounds(130, 120, 20, 20);

        lblhargaangklung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung.setText("Rp. 25.000");
        getContentPane().add(lblhargaangklung);
        lblhargaangklung.setBounds(110, 240, 50, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Blankon");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 110, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Angklung");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 110, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Besokap");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 110, 90, 30);

        jButton11.setText("RESET");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(490, 630, 130, 50);

        jButton12.setText("PESAN STOCK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(490, 350, 130, 140);

        jButton13.setText("TOTAL");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(490, 280, 130, 60);

        jButton14.setText("BACK");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(30, 60, 80, 40);

        jLabel3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("DISTRIBUTOR   A");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 60, 290, 30);
        getContentPane().add(alert1);
        alert1.setBounds(1370, 420, 262, 90);

        txtkonfirm.setColumns(20);
        txtkonfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonfirm.setRows(5);
        txtkonfirm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(txtkonfirm);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 280, 440, 350);

        txtTotalHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalHarga);
        txtTotalHarga.setBounds(30, 640, 440, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/bgbarang.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 10, 1040, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transbg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-170, -50, 1500, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.setVisible(false);
        new distributorframe().setVisible(true); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        if(Integer.parseInt(jmlangklung.getText())>0){
            jmlangklung.setText(Integer.toString(Integer.parseInt(jmlangklung.getText()) -1));
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jmlangklung.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlangklung.getText().equals(null)){
                             jmlangklung.setText("0");
                         }
                       
                             
                         }
                         catch(NumberFormatException e){
                             jmlangklung.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });  
        
        jmlangklung.setText(Integer.toString(Integer.parseInt(jmlangklung.getText()) + 1));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jmlbesokap.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlbesokap.getText().equals("")){
                             jmlbesokap.setText("0");
                         }
                                                      
                         }
                         catch(NumberFormatException e){
                             jmlbesokap.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlbesokap.setText(Integer.toString(Integer.parseInt(jmlbesokap.getText()) + 1));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        if(Integer.parseInt(jmlbesokap.getText())>0){
            jmlbesokap.setText(Integer.toString(Integer.parseInt(jmlbesokap.getText()) -1));
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jmlblankon.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlblankon.getText().equals(null)){
                             jmlblankon.setText("0");
                         }
                        
                             
                         }
                         catch(NumberFormatException e){
                             jmlblankon.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlblankon.setText(Integer.toString(Integer.parseInt(jmlblankon.getText()) + 1));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(jmlangklung.getText().equals("0") && jmlbesokap.getText().equals("0") && jmlblankon.getText().equals("0") && jmlbros.getText().equals("0") && jmlbukubelajar.getText().equals("0") && jmlbukucerita.getText().equals("0") && jmlbumbu.getText().equals("0")){
            alert1.showMessageDialog(null, "Tidak ada Barang yang dipesan!", "Perhatian!!", alert1.ERROR_MESSAGE);
        }else{
        
        
 
       jButton13.setEnabled(false);
       jButton12.setEnabled(true);
       
       jmlangklung.setEnabled(false);
       jmlbesokap.setEnabled(false);
       jmlblankon.setEnabled(false);
       jmlbros.setEnabled(false);
       jmlbukubelajar.setEnabled(false);
       jmlbukucerita.setEnabled(false);
       jmlbumbu.setEnabled(false);

       jButton1.setEnabled(false);
       jButton2.setEnabled(false);
       jButton3.setEnabled(false);
       jButton4.setEnabled(false);
       jButton5.setEnabled(false);
       jButton6.setEnabled(false);
       jButton7.setEnabled(false);
       jButton29.setEnabled(false);
       jButton30.setEnabled(false);
       jButton31.setEnabled(false);
       jButton32.setEnabled(false);
       jButton33.setEnabled(false);
       jButton34.setEnabled(false);
       jButton35.setEnabled(false);
       produk price = new produk();
       listTransaksi.add(" \t\t Meuli Point of Sale"
            + "\n\t\t Transaction Summary"
            + "\n====================================================="
            + "\nJumlah\t\t Nama Barang\t\t Harga");
    if(Integer.parseInt(jmlangklung.getText())> 0){
        totalHarga(price.getHargaAngklung()*Integer.parseInt(jmlangklung.getText()));
        listTransaksi.add(jmlangklung.getText() +"\t\t Angklung \t\t Rp. " + price.getHargaAngklung()*Integer.parseInt(jmlangklung.getText()));
    }
    if(Integer.parseInt(jmlbesokap.getText())> 0){
        totalHarga(price.getHargaBesokap()*Integer.parseInt(jmlbesokap.getText()));
        listTransaksi.add(jmlbesokap.getText() +"\t\t Besokap \t\t Rp. " + price.getHargaBesokap()*Integer.parseInt(jmlbesokap.getText()));
    }
    if(Integer.parseInt(jmlblankon.getText())> 0){
        totalHarga(price.getHargaBlankon()*Integer.parseInt(jmlblankon.getText()));
        listTransaksi.add(jmlblankon.getText() +"\t\t Blankon \t\t Rp. " + price.getHargaBlankon()*Integer.parseInt(jmlblankon.getText()));
    }
    if(Integer.parseInt(jmlbros.getText())> 0){
        totalHarga(price.getHargaBros()*Integer.parseInt(jmlbros.getText()));
        listTransaksi.add(jmlbros.getText() +"\t\t Bros \t\t\t Rp. " + price.getHargaBros()*Integer.parseInt(jmlbros.getText()));
    }
    if(Integer.parseInt(jmlbukubelajar.getText())> 0){
        totalHarga(price.getHargaBukuBelajar()*Integer.parseInt(jmlbukubelajar.getText()));
        listTransaksi.add(jmlbukubelajar.getText() +"\t\t Buku Belajar \t\t Rp. " + price.getHargaBukuBelajar()*Integer.parseInt(jmlbukubelajar.getText()));
    }
    if(Integer.parseInt(jmlbukucerita.getText())> 0){
        totalHarga(price.getHargaBukuCerita()*Integer.parseInt(jmlbukucerita.getText()));
        listTransaksi.add(jmlbukucerita.getText() +"\t\t Buku Cerita \t\t Rp. " + price.getHargaBukuCerita()*Integer.parseInt(jmlbukucerita.getText()));
    }
    if(Integer.parseInt(jmlbumbu.getText())> 0){
        totalHarga(price.getHargaBumbu()*Integer.parseInt(jmlbumbu.getText()));
        listTransaksi.add(jmlbumbu.getText() +"\t\t Bumbu \t\t\t Rp. " + price.getHargaBumbu()*Integer.parseInt(jmlbumbu.getText()));
    }
        transaksi = String.join("\n", listTransaksi);
        txtkonfirm.append(transaksi);
        txtTotalHarga.setText(Integer.toString(getTotalHarga()));
    
       }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
resetAll();       
transaksi = "";
jButton12.setEnabled(false);
  listTransaksi.clear();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jmlbros.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlbros.getText().equals(null)){
                             jmlbros.setText("0");
                         }
                        
                             
                         }
                         catch(NumberFormatException e){
                             jmlbros.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlbros.setText(Integer.toString(Integer.parseInt(jmlbros.getText()) + 1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     jmlbukubelajar.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlbukubelajar.getText().equals(null)){
                             jmlbukubelajar.setText("0");
                         }
                        
                             
                         }
                         catch(NumberFormatException e){
                             jmlbukubelajar.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlbukubelajar.setText(Integer.toString(Integer.parseInt(jmlbukubelajar.getText()) + 1));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      jmlbukucerita.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlbukucerita.getText().equals(null)){
                             jmlbukucerita.setText("0");
                         }
                        
                             
                         }
                         catch(NumberFormatException e){
                             jmlbukucerita.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlbukucerita.setText(Integer.toString(Integer.parseInt(jmlbukucerita.getText()) + 1));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jmlbumbu.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlbumbu.getText().equals(null)){
                             jmlbumbu.setText("0");
                         }
                        
                             
                         }
                         catch(NumberFormatException e){
                             jmlbumbu.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlbumbu.setText(Integer.toString(Integer.parseInt(jmlbumbu.getText()) + 1));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
     if(Integer.parseInt(jmlblankon.getText())>0){
            jmlblankon.setText(Integer.toString(Integer.parseInt(jmlblankon.getText()) -1));
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
     if(Integer.parseInt(jmlbros.getText())>0){
            jmlbros.setText(Integer.toString(Integer.parseInt(jmlbros.getText()) -1));
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
       if(Integer.parseInt(jmlbukubelajar.getText())>0){
            jmlbukubelajar.setText(Integer.toString(Integer.parseInt(jmlbukubelajar.getText()) -1));
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        if(Integer.parseInt(jmlbukucerita.getText())>0){
            jmlbukucerita.setText(Integer.toString(Integer.parseInt(jmlbukucerita.getText()) -1));
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
      if(Integer.parseInt(jmlbumbu.getText())>0){
            jmlbumbu.setText(Integer.toString(Integer.parseInt(jmlbumbu.getText()) -1));
        }
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        alert1.showMessageDialog(null, "Transaksi Pemesanan Stock Berhasil!", "Berhasil!", alert1.INFORMATION_MESSAGE);
        pembelian obj = new pembelian();
        obj.setTotalPengeluaran(obj.getTotalPengeluaran()+Integer.parseInt(txtTotalHarga.getText()));
        obj.listPembelianDistributorA.add(transaksi);
        //alert1.showMessageDialog(null, Arrays.toString(obj.listPembelianDistributorA.toArray()), "Perhatian!!", alert1.ERROR_MESSAGE);
        dashboard pw = new dashboard();
        pw.totalbeli += Integer.parseInt(txtTotalHarga.getText());
        
        tambahStock();
        recordStock();
        jButton12.setEnabled(false);
        mulaiTransaksi();
       
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(distributorAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(distributorAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(distributorAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(distributorAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new distributorAFrame().setVisible(true);
            }
        });
        
       
    }
    
    public void setHarga(){
        distributorA obj = new distributorA();
        lblhargaangklung.setText("Rp. " + obj.getDistAngklung());
        lblhargabesokap.setText("Rp. " + obj.getDistBesokap());
        lblhargablankon.setText("Rp. " + obj.getDistBlankon());
        lblhargabros.setText("Rp. "+ obj.getDistBros());
        lblhargabukubelajar.setText("Rp. " + obj.getDistBukuBelajar());
        lblhargabukucerita.setText("Rp. " + obj.getDistBukuCerita());
        lblhargabumbu.setText("Rp. " + obj.getDistBumbu());
    }
    
    public void tambahStock(){
         produk obj = new produk();
        
       
obj.setStockAngklung(obj.getStockAngklung()+Integer.parseInt(jmlangklung.getText()));
obj.setStockBesokap(obj.getStockBesokap()+Integer.parseInt(jmlbesokap.getText()));
obj.setStockBlankon(obj.getStockBlankon()+Integer.parseInt(jmlblankon.getText()));
obj.setStockBros(obj.getStockBros()+Integer.parseInt(jmlbros.getText()));
obj.setStockBukuBelajar(obj.getStockBukuBelajar()+Integer.parseInt(jmlbukubelajar.getText()));
obj.setStockBukuCerita(obj.getStockBukuCerita()+Integer.parseInt(jmlbukucerita.getText()));
obj.setStockBumbu(obj.getStockBumbu()+Integer.parseInt(jmlbumbu.getText()));


//  listTransaksi.add(jmlangklung.getText() +"\t\t Angklung \t\t Rp. " + price.getHargaAngklung()*Integer.parseInt(jmlangklung.getText()));

    }
    
    public void recordStock(){
     pembelian obj = new pembelian();
  
    obj.recordAngklung += Integer.parseInt(jmlangklung.getText());
    obj.recordBesokap += Integer.parseInt(jmlbesokap.getText());
    obj.recordBlankon += Integer.parseInt(jmlblankon.getText());
    obj.recordBros += Integer.parseInt(jmlbros.getText());
    obj.recordBukuBelajar += Integer.parseInt(jmlbukubelajar.getText());
    obj.recordBukuCerita += Integer.parseInt(jmlbukucerita.getText());
    obj.recordBumbu += Integer.parseInt(jmlbumbu.getText());
   
    }
    
    
    public void mulaiTransaksi(){
         produk obj = new produk();
         lblstockangklung.setText(Integer.toString(obj.getStockAngklung()));
    lblstockbesokap.setText(Integer.toString(obj.getStockBesokap()));
    lblstockblankon.setText(Integer.toString(obj.getStockBlankon()));
    lblstockbros.setText(Integer.toString(obj.getStockBros()));
    lblstockbukubelajar.setText(Integer.toString(obj.getStockBukuBelajar()));
    lblstockbukucerita.setText(Integer.toString(obj.getStockBukuCerita()));
    lblstockbumbu.setText(Integer.toString(obj.getStockBumbu()));
    }
    
    public void resetAll(){
        txtTotalHarga.setText("");
        txtkonfirm.setText("");
        jButton13.setEnabled(true);
        jButton12.setEnabled(true);
       jmlangklung.setText("0");
       jmlbesokap.setText("0");
       jmlblankon.setText("0");
       jmlbros.setText("0");
       jmlbukubelajar.setText("0");
       jmlbukucerita.setText("0");
       jmlbumbu.setText("0");
       
       jmlangklung.setEnabled(true);
       jmlbesokap.setEnabled(true);
       jmlblankon.setEnabled(true);
       jmlbros.setEnabled(true);
       jmlbukubelajar.setEnabled(true);
       jmlbukucerita.setEnabled(true);
       jmlbumbu.setEnabled(true);

       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton29.setEnabled(true);
       jButton30.setEnabled(true);
       jButton31.setEnabled(true);
       jButton32.setEnabled(true);
       jButton33.setEnabled(true);
       jButton34.setEnabled(true);
       jButton35.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlangklung;
    private javax.swing.JTextField jmlbesokap;
    private javax.swing.JTextField jmlblankon;
    private javax.swing.JTextField jmlbros;
    private javax.swing.JTextField jmlbukubelajar;
    private javax.swing.JTextField jmlbukucerita;
    private javax.swing.JTextField jmlbumbu;
    private javax.swing.JLabel lblhargaangklung;
    private javax.swing.JLabel lblhargabesokap;
    private javax.swing.JLabel lblhargablankon;
    private javax.swing.JLabel lblhargabros;
    private javax.swing.JLabel lblhargabukubelajar;
    private javax.swing.JLabel lblhargabukucerita;
    private javax.swing.JLabel lblhargabumbu;
    private javax.swing.JLabel lblstockangklung;
    private javax.swing.JLabel lblstockbesokap;
    private javax.swing.JLabel lblstockblankon;
    private javax.swing.JLabel lblstockbros;
    private javax.swing.JLabel lblstockbukubelajar;
    private javax.swing.JLabel lblstockbukucerita;
    private javax.swing.JLabel lblstockbumbu;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextArea txtkonfirm;
    // End of variables declaration//GEN-END:variables
}
