/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import laporan.dashboard;
import laporan.pembelian;
import manageproduk.produk;
import meuli.distributor.distributorA;
/**
 *
 * @author thero
 */
public class distributorDFrame extends javax.swing.JFrame {
 public ArrayList<String> listTransaksi = new ArrayList<String>();
    private int harga = 0;
    public String transaksi;

    /**
     * Creates new form distributorAFrame
     */
    public distributorDFrame() {
       initComponents();
        distributorD obj = new distributorD();
        lblhargasasakala.setText("Rp. " +obj.getDistSasakala());
        lblhargasiger.setText("Rp. " + obj.getDistSiger());
        lblhargasimpay.setText("Rp. " + obj.getDistSimpay());
        lblhargasuling.setText("Rp. " + obj.getDistSuling());
        lblhargasales.setText("Rp. " + obj.getDistTales());
        lblhargatotopong.setText("Rp. " + obj.getDistTotopong());
        lblhargaudeng.setText("Rp. " + obj.getDistUdeng());
       jButton12.setEnabled(false);
    }
    
    public void totalHarga(int x){
        harga+=x;
    }
    public int getTotalHarga(){
        return harga;
    }
    
    public void resetHarga(){
        harga = 0;
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        lblstocksasakala = new javax.swing.JLabel();
        lblhargasasakala = new javax.swing.JLabel();
        lblstocksiger = new javax.swing.JLabel();
        lblhargasiger = new javax.swing.JLabel();
        lblstocksimpay = new javax.swing.JLabel();
        lblhargasimpay = new javax.swing.JLabel();
        lblstocksuling = new javax.swing.JLabel();
        lblhargasuling = new javax.swing.JLabel();
        lblstocktales = new javax.swing.JLabel();
        lblhargasales = new javax.swing.JLabel();
        lblstocktotopong = new javax.swing.JLabel();
        lblhargatotopong = new javax.swing.JLabel();
        lblstockudeng = new javax.swing.JLabel();
        lblhargaudeng = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jmludeng = new javax.swing.JTextField();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jmltotopong = new javax.swing.JTextField();
        jButton52 = new javax.swing.JButton();
        jmltales = new javax.swing.JTextField();
        jButton53 = new javax.swing.JButton();
        jmlsuling = new javax.swing.JTextField();
        jButton54 = new javax.swing.JButton();
        jmlsimpay = new javax.swing.JTextField();
        jButton55 = new javax.swing.JButton();
        jmlsiger = new javax.swing.JTextField();
        jButton56 = new javax.swing.JButton();
        jmlsasakala = new javax.swing.JTextField();
        alert1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtkonfirm = new javax.swing.JTextArea();
        txtTotalHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(null);

        jButton11.setText("RESET");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(480, 620, 130, 60);

        jButton12.setText("PESAN STOCK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(480, 350, 130, 140);

        jButton13.setText("TOTAL");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(480, 280, 130, 60);

        jButton14.setText("BACK");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(40, 30, 110, 60);

        jLabel3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("DISTRIBUTOR  D");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 60, 290, 30);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/sasakalaSunda17000.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(30, 140, 130, 100);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/SigerAnak55000.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(170, 140, 130, 100);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/SimpayBasaSunda98000.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(310, 140, 130, 100);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/suling10000.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(450, 140, 130, 100);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/tales15000.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26);
        jButton26.setBounds(590, 140, 130, 100);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/totopong12000.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(730, 140, 130, 100);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/udeng75000.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(870, 140, 130, 100);

        lblstocksasakala.setText("5");
        getContentPane().add(lblstocksasakala);
        lblstocksasakala.setBounds(140, 120, 10, 20);

        lblhargasasakala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasasakala.setText("Rp. 25.000");
        getContentPane().add(lblhargasasakala);
        lblhargasasakala.setBounds(110, 240, 60, 20);

        lblstocksiger.setText("5");
        getContentPane().add(lblstocksiger);
        lblstocksiger.setBounds(280, 120, 10, 20);

        lblhargasiger.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasiger.setText("Rp. 25.000");
        getContentPane().add(lblhargasiger);
        lblhargasiger.setBounds(250, 240, 60, 20);

        lblstocksimpay.setText("5");
        getContentPane().add(lblstocksimpay);
        lblstocksimpay.setBounds(420, 120, 10, 20);

        lblhargasimpay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasimpay.setText("Rp. 25.000");
        getContentPane().add(lblhargasimpay);
        lblhargasimpay.setBounds(390, 240, 60, 20);

        lblstocksuling.setText("5");
        getContentPane().add(lblstocksuling);
        lblstocksuling.setBounds(560, 120, 10, 20);

        lblhargasuling.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasuling.setText("Rp. 25.000");
        getContentPane().add(lblhargasuling);
        lblhargasuling.setBounds(530, 240, 60, 20);

        lblstocktales.setText("5");
        getContentPane().add(lblstocktales);
        lblstocktales.setBounds(700, 120, 10, 20);

        lblhargasales.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasales.setText("Rp. 25.000");
        getContentPane().add(lblhargasales);
        lblhargasales.setBounds(670, 240, 60, 20);

        lblstocktotopong.setText("5");
        getContentPane().add(lblstocktotopong);
        lblstocktotopong.setBounds(840, 120, 10, 20);

        lblhargatotopong.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargatotopong.setText("Rp. 25.000");
        getContentPane().add(lblhargatotopong);
        lblhargatotopong.setBounds(810, 240, 60, 20);

        lblstockudeng.setText("5");
        getContentPane().add(lblstockudeng);
        lblstockudeng.setBounds(980, 120, 10, 20);

        lblhargaudeng.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaudeng.setText("Rp. 25.000");
        getContentPane().add(lblhargaudeng);
        lblhargaudeng.setBounds(950, 240, 60, 20);

        jLabel110.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel110.setText("Udeng");
        getContentPane().add(jLabel110);
        jLabel110.setBounds(870, 110, 130, 30);

        jLabel111.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel111.setText("Totopong");
        getContentPane().add(jLabel111);
        jLabel111.setBounds(730, 110, 70, 30);

        jLabel112.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel112.setText("Tales");
        getContentPane().add(jLabel112);
        jLabel112.setBounds(590, 110, 110, 30);

        jLabel113.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel113.setText("Suling");
        getContentPane().add(jLabel113);
        jLabel113.setBounds(450, 110, 80, 30);

        jLabel114.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel114.setText("Simpay");
        getContentPane().add(jLabel114);
        jLabel114.setBounds(310, 110, 150, 30);

        jLabel115.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel115.setText("Siger");
        getContentPane().add(jLabel115);
        jLabel115.setBounds(170, 110, 50, 30);

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel116.setText("Sasakala");
        getContentPane().add(jLabel116);
        jLabel116.setBounds(30, 110, 110, 30);

        jmludeng.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmludeng.setText("0");
        getContentPane().add(jmludeng);
        jmludeng.setBounds(910, 240, 30, 20);

        jButton50.setText("-");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton50);
        jButton50.setBounds(870, 240, 37, 20);

        jButton51.setText("-");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51);
        jButton51.setBounds(730, 240, 37, 20);

        jmltotopong.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmltotopong.setText("0");
        getContentPane().add(jmltotopong);
        jmltotopong.setBounds(770, 240, 30, 20);

        jButton52.setText("-");
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton52);
        jButton52.setBounds(590, 240, 37, 20);

        jmltales.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmltales.setText("0");
        getContentPane().add(jmltales);
        jmltales.setBounds(630, 240, 30, 20);

        jButton53.setText("-");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton53);
        jButton53.setBounds(450, 240, 37, 20);

        jmlsuling.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsuling.setText("0");
        getContentPane().add(jmlsuling);
        jmlsuling.setBounds(490, 240, 30, 20);

        jButton54.setText("-");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton54);
        jButton54.setBounds(310, 240, 37, 20);

        jmlsimpay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsimpay.setText("0");
        getContentPane().add(jmlsimpay);
        jmlsimpay.setBounds(350, 240, 30, 20);

        jButton55.setText("-");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton55);
        jButton55.setBounds(170, 240, 37, 20);

        jmlsiger.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsiger.setText("0");
        getContentPane().add(jmlsiger);
        jmlsiger.setBounds(210, 240, 30, 20);

        jButton56.setText("-");
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton56);
        jButton56.setBounds(30, 240, 37, 20);

        jmlsasakala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsasakala.setText("0");
        getContentPane().add(jmlsasakala);
        jmlsasakala.setBounds(70, 240, 30, 20);
        getContentPane().add(alert1);
        alert1.setBounds(1270, 410, 262, 90);

        txtkonfirm.setColumns(20);
        txtkonfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonfirm.setRows(5);
        txtkonfirm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(txtkonfirm);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 280, 440, 350);

        txtTotalHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalHarga);
        txtTotalHarga.setBounds(30, 640, 440, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/bgbarang.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 20, 1040, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transbg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-170, -50, 1500, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.setVisible(false);
        new distributorframe().setVisible(true); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
if(jmlsasakala.getText().equals("0") && jmlsiger.getText().equals("0") && jmlsimpay.getText().equals("0") && jmlsuling.getText().equals("0") && jmltales.getText().equals("0") && jmltotopong.getText().equals("0") && jmludeng.getText().equals("0")){
            alert1.showMessageDialog(null, "Tidak ada Barang yang dipesan!", "Perhatian!!", alert1.ERROR_MESSAGE);
        }else{
    
     jButton13.setEnabled(false);
       jButton12.setEnabled(true);
           
       
    jmlsasakala.setEnabled(false);
       jmlsiger.setEnabled(false);
       jmlsimpay.setEnabled(false);
       jmlsuling.setEnabled(false);
       jmltales.setEnabled(false);
       jmltotopong.setEnabled(false);
       jmludeng.setEnabled(false);

       jButton22.setEnabled(false);
       jButton23.setEnabled(false);
       jButton24.setEnabled(false);
       jButton25.setEnabled(false);
       jButton26.setEnabled(false);
       jButton27.setEnabled(false);
       jButton28.setEnabled(false);
       
       jButton50.setEnabled(false);
       jButton51.setEnabled(false);
       jButton52.setEnabled(false);
       jButton53.setEnabled(false);
       jButton54.setEnabled(false);
       jButton55.setEnabled(false);
       jButton56.setEnabled(false);
        produk price = new produk(); 
        listTransaksi.add(" \t\t Meuli Point of Sale"
            + "\n\t\t Transaction Summary"
            + "\n====================================================="
            + "\nJumlah\t\t Nama Barang\t\t Harga");
       
      if(Integer.parseInt(jmlsasakala.getText())> 0){
        totalHarga(price.getHargaSasakala()*Integer.parseInt(jmlsasakala.getText()));
        listTransaksi.add(jmlsasakala.getText() +"\t\t Sasakala \t\t Rp. " + price.getHargaSasakala()*Integer.parseInt(jmlsasakala.getText()));
    }
    if(Integer.parseInt(jmlsiger.getText())> 0){
        totalHarga(price.getHargaSiger()*Integer.parseInt(jmlsiger.getText()));
        listTransaksi.add(jmlsiger.getText() +"\t\t Siger \t\t\t Rp. " + price.getHargaSiger()*Integer.parseInt(jmlsiger.getText()));
    }
    if(Integer.parseInt(jmlsimpay.getText())> 0){
        totalHarga(price.getHargaSimpay()*Integer.parseInt(jmlsimpay.getText()));
        listTransaksi.add(jmlsimpay.getText() +"\t\t Simpay \t\t Rp. " + price.getHargaSimpay()*Integer.parseInt(jmlsimpay.getText()));
    }
    if(Integer.parseInt(jmlsuling.getText())> 0){
        totalHarga(price.getHargaSuling()*Integer.parseInt(jmlsuling.getText()));
        listTransaksi.add(jmlsuling.getText() +"\t\t Suling \t\t Rp. " + price.getHargaSuling()*Integer.parseInt(jmlsuling.getText()));
    }
    if(Integer.parseInt(jmltales.getText())> 0){
        totalHarga(price.getHargaTales()*Integer.parseInt(jmltales.getText()));
        listTransaksi.add(jmltales.getText() +"\t\t Tales \t\t\t Rp. " + price.getHargaTales()*Integer.parseInt(jmltales.getText()));
    }
    if(Integer.parseInt(jmltotopong.getText())> 0){
        totalHarga(price.getHargaTotopong()*Integer.parseInt(jmltotopong.getText()));
        listTransaksi.add(jmltotopong.getText() +"\t\t Totopong \t\t Rp. " + price.getHargaTotopong()*Integer.parseInt(jmltotopong.getText()));
    }
    if(Integer.parseInt(jmludeng.getText())> 0){
        totalHarga(price.getHargaUdeng()*Integer.parseInt(jmludeng.getText()));
        listTransaksi.add(jmludeng.getText() +"\t\t Udeng \t\t\t Rp. " + price.getHargaUdeng()*Integer.parseInt(jmludeng.getText()));
    }
    
    transaksi = String.join("\n", listTransaksi);
        txtkonfirm.append(transaksi);
        txtTotalHarga.setText(Integer.toString(getTotalHarga()));
        
       
} 
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
jButton12.setEnabled(false);       
        resetAll();
        transaksi = "";
          listTransaksi.clear();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
         if(Integer.parseInt(jmlsasakala.getText())>0){
            jmlsasakala.setText(Integer.toString(Integer.parseInt(jmlsasakala.getText()) -1));
        }
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
            jmlsasakala.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlsasakala.getText().equals(null)){
                             jmlsasakala.setText("0");
                         }
                         if (Integer.parseInt(jmlsasakala.getText()) > obj.getStockSasakala()){
                        
                         jmlsasakala.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlsasakala.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlsasakala.setText(Integer.toString(Integer.parseInt(jmlsasakala.getText()) + 1));
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
          if(Integer.parseInt(jmlsiger.getText())>0){
            jmlsiger.setText(Integer.toString(Integer.parseInt(jmlsiger.getText()) -1));
        }
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
      jmlsiger.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlsiger.getText().equals(null)){
                             jmlsiger.setText("0");
                         }
                         if (Integer.parseInt(jmlsiger.getText()) > obj.getStockSiger()){
                        
                         jmlsiger.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlsiger.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlsiger.setText(Integer.toString(Integer.parseInt(jmlsiger.getText()) + 1));
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        jmlsimpay.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlsimpay.getText().equals(null)){
                             jmlsimpay.setText("0");
                         }
                         if (Integer.parseInt(jmlsimpay.getText()) > obj.getStockSimpay()){
                        
                         jmlsimpay.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlsimpay.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlsimpay.setText(Integer.toString(Integer.parseInt(jmlsimpay.getText()) + 1));
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        if(Integer.parseInt(jmlsimpay.getText())>0){
            jmlsimpay.setText(Integer.toString(Integer.parseInt(jmlsimpay.getText()) -1));
        }
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        if(Integer.parseInt(jmlsuling.getText())>0){
            jmlsuling.setText(Integer.toString(Integer.parseInt(jmlsuling.getText()) -1));
        }
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
       jmlsuling.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlsuling.getText().equals(null)){
                             jmlsuling.setText("0");
                         }
                         if (Integer.parseInt(jmlsuling.getText()) > obj.getStockSuling()){
                        
                         jmlsuling.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlsuling.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlsuling.setText(Integer.toString(Integer.parseInt(jmlsuling.getText()) + 1));
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        if(Integer.parseInt(jmltales.getText())>0){
            jmltales.setText(Integer.toString(Integer.parseInt(jmltales.getText()) -1));
        }
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
       jmltales.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmltales.getText().equals(null)){
                             jmltales.setText("0");
                         }
                         if (Integer.parseInt(jmltales.getText()) > obj.getStockTales()){
                        
                         jmltales.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmltales.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmltales.setText(Integer.toString(Integer.parseInt(jmltales.getText()) + 1));
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        if(Integer.parseInt(jmltotopong.getText())>0){
            jmltotopong.setText(Integer.toString(Integer.parseInt(jmltotopong.getText()) -1));
        }
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
         jmltotopong.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmltotopong.getText().equals(null)){
                             jmltotopong.setText("0");
                         }
                         if (Integer.parseInt(jmltotopong.getText()) > obj.getStockTotopong()){
                        
                         jmltotopong.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmltotopong.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmltotopong.setText(Integer.toString(Integer.parseInt(jmltotopong.getText()) + 1));
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
      jmludeng.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmludeng.getText().equals(null)){
                             jmludeng.setText("0");
                         }
                         if (Integer.parseInt(jmludeng.getText()) > obj.getStockUdeng()){
                        
                         jmludeng.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmludeng.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmludeng.setText(Integer.toString(Integer.parseInt(jmludeng.getText()) + 1));
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        if(Integer.parseInt(jmludeng.getText())>0){
            jmludeng.setText(Integer.toString(Integer.parseInt(jmludeng.getText()) -1));
        }
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        alert1.showMessageDialog(null, "Transaksi Pemesanan Stock Berhasil!", "Berhasil!", alert1.INFORMATION_MESSAGE);
        pembelian obj = new pembelian();
        obj.setTotalPengeluaran(obj.getTotalPengeluaran()+Integer.parseInt(txtTotalHarga.getText()));
        obj.listPembelianDistributorD.add(transaksi);
        dashboard pw = new dashboard();
        pw.totalbeli += Integer.parseInt(txtTotalHarga.getText());
        
        tambahStock();
        jButton12.setEnabled(false);
        mulaiTransaksi();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(distributorDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(distributorDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(distributorDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(distributorDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new distributorDFrame().setVisible(true);
            }
        });
        
       
    }
    
    public void setHarga(){
        distributorD obj = new distributorD();
        lblhargasasakala.setText("Rp. " +obj.getDistSasakala());
        lblhargasiger.setText("Rp. " + obj.getDistSiger());
        lblhargasimpay.setText("Rp. " + obj.getDistSimpay());
        lblhargasuling.setText("Rp. " + obj.getDistSuling());
        lblhargasales.setText("Rp. " + obj.getDistTales());
        lblhargatotopong.setText("Rp. " + obj.getDistTotopong());
        lblhargaudeng.setText("Rp. " + obj.getDistUdeng());
        
    }
    
    public void tambahStock(){
         produk obj = new produk();
        
       
obj.setStockSasakala(obj.getStockSasakala()+Integer.parseInt(jmlsasakala.getText()));
obj.setStockSiger(obj.getStockSiger()+Integer.parseInt(jmlsiger.getText()));
obj.setStockSimpay(obj.getStockSimpay()+Integer.parseInt(jmlsimpay.getText()));
obj.setStockSuling(obj.getStockSuling()+Integer.parseInt(jmlsuling.getText()));
obj.setStockTales(obj.getStockTales()+Integer.parseInt(jmltales.getText()));
obj.setStockTotopong(obj.getStockTotopong()+Integer.parseInt(jmltotopong.getText()));
obj.setStockUdeng(obj.getStockUdeng()+Integer.parseInt(jmludeng.getText()));
    }
    
    public void mulaiTransaksi(){
         produk obj = new produk();
        lblstocksasakala.setText(Integer.toString(obj.getStockSasakala()));
    lblstocksiger.setText(Integer.toString(obj.getStockSiger()));
    lblstocksimpay.setText(Integer.toString(obj.getStockSimpay()));
    lblstocksuling.setText(Integer.toString(obj.getStockSuling()));
    lblstocktales.setText(Integer.toString(obj.getStockTales()));
    lblstocktotopong.setText(Integer.toString(obj.getStockTotopong()));
    lblstockudeng.setText(Integer.toString(obj.getStockUdeng()));
    }
    
    public void resetAll(){
        txtTotalHarga.setText("");
        txtkonfirm.setText("");
        jButton13.setEnabled(true);
        jButton12.setEnabled(true);
       jmlsasakala.setEnabled(true);
       jmlsiger.setEnabled(true);
       jmlsimpay.setEnabled(true);
       jmlsuling.setEnabled(true);
       jmltales.setEnabled(true);
       jmltotopong.setEnabled(true);
       jmludeng.setEnabled(true);
       
       jmlsasakala.setText("0");
       jmlsiger.setText("0");
       jmlsimpay.setText("0");
       jmlsuling.setText("0");
       jmltales.setText("0");
       jmltotopong.setText("0");
       jmludeng.setText("0");
        
       jButton22.setEnabled(true);
       jButton23.setEnabled(true);
       jButton24.setEnabled(true);
       jButton25.setEnabled(true);
       jButton26.setEnabled(true);
       jButton27.setEnabled(true);
       jButton28.setEnabled(true);
       jButton50.setEnabled(true);
       jButton51.setEnabled(true);
       jButton52.setEnabled(true);
       jButton53.setEnabled(true);
       jButton54.setEnabled(true);
       jButton55.setEnabled(true);
       jButton56.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlsasakala;
    private javax.swing.JTextField jmlsiger;
    private javax.swing.JTextField jmlsimpay;
    private javax.swing.JTextField jmlsuling;
    private javax.swing.JTextField jmltales;
    private javax.swing.JTextField jmltotopong;
    private javax.swing.JTextField jmludeng;
    private javax.swing.JLabel lblhargasales;
    private javax.swing.JLabel lblhargasasakala;
    private javax.swing.JLabel lblhargasiger;
    private javax.swing.JLabel lblhargasimpay;
    private javax.swing.JLabel lblhargasuling;
    private javax.swing.JLabel lblhargatotopong;
    private javax.swing.JLabel lblhargaudeng;
    private javax.swing.JLabel lblstocksasakala;
    private javax.swing.JLabel lblstocksiger;
    private javax.swing.JLabel lblstocksimpay;
    private javax.swing.JLabel lblstocksuling;
    private javax.swing.JLabel lblstocktales;
    private javax.swing.JLabel lblstocktotopong;
    private javax.swing.JLabel lblstockudeng;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextArea txtkonfirm;
    // End of variables declaration//GEN-END:variables
}
