/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import laporan.dashboard;
import laporan.pembelian;
import manageproduk.produk;
import meuli.distributor.distributorA;
/**
 *
 * @author thero
 */
public class distributorCFrame extends javax.swing.JFrame {
 public ArrayList<String> listTransaksi = new ArrayList<String>();
    private int harga = 0;
    public String transaksi;

    /**
     * Creates new form distributorAFrame
     */
    public distributorCFrame() {
       initComponents();
      distributorC obj = new distributorC();
        lblhargamahkota.setText("Rp. " + obj.getDistMahkota());
        lblhargapangrumat.setText("Rp. " + obj.getDistPangrumat());
        lblhargapangsi.setText("Rp. " + obj.getDistPangsi());
        lblhargaperang.setText("Rp. " + obj.getDistPerang());
        lblhargapisang.setText("Rp. " + obj.getDistPisang());
        lblhargapusaka.setText("Rp. " + obj.getDistPustaka());
        lblhargarumah.setText("Rp. "+ obj.getDistRumah());
       jButton12.setEnabled(false);
    }
    
    
    public void totalHarga(int x){
        harga+=x;
    }
    public int getTotalHarga(){
        return harga;
    }
    
    public void resetHarga(){
        harga = 0;
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        lblstockmahkota = new javax.swing.JLabel();
        lblhargamahkota = new javax.swing.JLabel();
        lblstockpangrumat = new javax.swing.JLabel();
        lblhargapangrumat = new javax.swing.JLabel();
        lblstockpangsi = new javax.swing.JLabel();
        lblhargapangsi = new javax.swing.JLabel();
        lblstockperang = new javax.swing.JLabel();
        lblhargaperang = new javax.swing.JLabel();
        lblstockpisang = new javax.swing.JLabel();
        lblhargapisang = new javax.swing.JLabel();
        lblstockpusaka = new javax.swing.JLabel();
        lblhargapusaka = new javax.swing.JLabel();
        lblstockrumah = new javax.swing.JLabel();
        lblhargarumah = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jmlrumah = new javax.swing.JTextField();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jmlpusaka = new javax.swing.JTextField();
        jButton45 = new javax.swing.JButton();
        jmlpisang = new javax.swing.JTextField();
        jButton46 = new javax.swing.JButton();
        jmlperang = new javax.swing.JTextField();
        jButton47 = new javax.swing.JButton();
        jmlpangsi = new javax.swing.JTextField();
        jButton48 = new javax.swing.JButton();
        jmlpangrumat = new javax.swing.JTextField();
        jButton49 = new javax.swing.JButton();
        jmlmahkota = new javax.swing.JTextField();
        alert1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtkonfirm = new javax.swing.JTextArea();
        txtTotalHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(null);

        jButton11.setText("RESET");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(490, 620, 130, 60);

        jButton12.setText("PESAN STOCK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(490, 340, 130, 140);

        jButton13.setText("TOTAL");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(490, 280, 130, 60);

        jButton14.setText("BACK");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(30, 20, 110, 50);

        jLabel3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("DISTRIBUTOR   C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 60, 290, 30);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/Mahkota190000.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(30, 140, 130, 100);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pangrumatSunda20000.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(170, 140, 130, 100);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pangsi80000.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(310, 140, 130, 100);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/perangBubat28000.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(450, 140, 130, 100);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pisangSale25000.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(590, 140, 130, 100);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/pustakabasa20000.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(730, 140, 130, 100);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/RumahMiniatur60000.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(870, 140, 130, 100);

        lblstockmahkota.setText("5");
        getContentPane().add(lblstockmahkota);
        lblstockmahkota.setBounds(140, 120, 10, 20);

        lblhargamahkota.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargamahkota.setText("Rp. 25.000");
        getContentPane().add(lblhargamahkota);
        lblhargamahkota.setBounds(110, 240, 60, 20);

        lblstockpangrumat.setText("5");
        getContentPane().add(lblstockpangrumat);
        lblstockpangrumat.setBounds(280, 120, 10, 20);

        lblhargapangrumat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapangrumat.setText("Rp. 25.000");
        getContentPane().add(lblhargapangrumat);
        lblhargapangrumat.setBounds(250, 240, 60, 20);

        lblstockpangsi.setText("5");
        getContentPane().add(lblstockpangsi);
        lblstockpangsi.setBounds(420, 120, 10, 20);

        lblhargapangsi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapangsi.setText("Rp. 25.000");
        getContentPane().add(lblhargapangsi);
        lblhargapangsi.setBounds(390, 240, 60, 20);

        lblstockperang.setText("5");
        getContentPane().add(lblstockperang);
        lblstockperang.setBounds(570, 120, 10, 20);

        lblhargaperang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaperang.setText("Rp.25.000");
        getContentPane().add(lblhargaperang);
        lblhargaperang.setBounds(530, 240, 60, 20);

        lblstockpisang.setText("5");
        getContentPane().add(lblstockpisang);
        lblstockpisang.setBounds(700, 120, 10, 20);

        lblhargapisang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapisang.setText("Rp. 25.000");
        getContentPane().add(lblhargapisang);
        lblhargapisang.setBounds(670, 240, 60, 20);

        lblstockpusaka.setText("5");
        getContentPane().add(lblstockpusaka);
        lblstockpusaka.setBounds(840, 120, 10, 20);

        lblhargapusaka.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargapusaka.setText("Rp. 25.000");
        getContentPane().add(lblhargapusaka);
        lblhargapusaka.setBounds(810, 240, 60, 20);

        lblstockrumah.setText("5");
        getContentPane().add(lblstockrumah);
        lblstockrumah.setBounds(980, 120, 10, 20);

        lblhargarumah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargarumah.setText("Rp. 25.000");
        getContentPane().add(lblhargarumah);
        lblhargarumah.setBounds(950, 240, 60, 20);

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel82.setText("Rumah");
        getContentPane().add(jLabel82);
        jLabel82.setBounds(870, 110, 49, 30);

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel83.setText("Pusaka");
        getContentPane().add(jLabel83);
        jLabel83.setBounds(730, 110, 100, 30);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setText("Pisang");
        getContentPane().add(jLabel84);
        jLabel84.setBounds(590, 110, 100, 30);

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel85.setText("Perang");
        getContentPane().add(jLabel85);
        jLabel85.setBounds(450, 110, 110, 30);

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel86.setText("Pangsi");
        getContentPane().add(jLabel86);
        jLabel86.setBounds(310, 110, 80, 30);

        jLabel87.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel87.setText("Pangrumat");
        getContentPane().add(jLabel87);
        jLabel87.setBounds(170, 110, 100, 30);

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel88.setText("Mahkota");
        getContentPane().add(jLabel88);
        jLabel88.setBounds(30, 110, 60, 30);

        jmlrumah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlrumah.setText("0");
        getContentPane().add(jmlrumah);
        jmlrumah.setBounds(910, 240, 30, 20);

        jButton43.setText("-");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43);
        jButton43.setBounds(870, 240, 37, 20);

        jButton44.setText("-");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton44);
        jButton44.setBounds(730, 240, 37, 20);

        jmlpusaka.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpusaka.setText("0");
        getContentPane().add(jmlpusaka);
        jmlpusaka.setBounds(770, 240, 30, 20);

        jButton45.setText("-");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton45);
        jButton45.setBounds(590, 240, 37, 20);

        jmlpisang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpisang.setText("0");
        getContentPane().add(jmlpisang);
        jmlpisang.setBounds(630, 240, 30, 20);

        jButton46.setText("-");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton46);
        jButton46.setBounds(450, 240, 37, 20);

        jmlperang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlperang.setText("0");
        getContentPane().add(jmlperang);
        jmlperang.setBounds(490, 240, 30, 20);

        jButton47.setText("-");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton47);
        jButton47.setBounds(310, 240, 37, 20);

        jmlpangsi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpangsi.setText("0");
        getContentPane().add(jmlpangsi);
        jmlpangsi.setBounds(350, 240, 30, 20);

        jButton48.setText("-");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton48);
        jButton48.setBounds(170, 240, 37, 20);

        jmlpangrumat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlpangrumat.setText("0");
        getContentPane().add(jmlpangrumat);
        jmlpangrumat.setBounds(210, 240, 30, 20);

        jButton49.setText("-");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton49);
        jButton49.setBounds(30, 240, 37, 20);

        jmlmahkota.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlmahkota.setText("0");
        getContentPane().add(jmlmahkota);
        jmlmahkota.setBounds(70, 240, 30, 20);
        getContentPane().add(alert1);
        alert1.setBounds(1500, 360, 262, 90);

        txtkonfirm.setColumns(20);
        txtkonfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonfirm.setRows(5);
        txtkonfirm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(txtkonfirm);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 280, 440, 350);

        txtTotalHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalHarga);
        txtTotalHarga.setBounds(30, 640, 440, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/bgbarang.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 10, 1040, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transbg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-170, -50, 1500, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
         this.setVisible(false);
        new distributorframe().setVisible(true); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       
        if(jmlmahkota.getText().equals("0") && jmlpangrumat.getText().equals("0") && jmlpangsi.getText().equals("0") && jmlperang.getText().equals("0") && jmlpisang.getText().equals("0") && jmlpusaka.getText().equals("0") && jmlrumah.getText().equals("0")){
            alert1.showMessageDialog(null, "Tidak ada Barang yang dipesan!", "Perhatian!!", alert1.ERROR_MESSAGE);
        }else{
              
       jButton13.setEnabled(false);
       jButton12.setEnabled(true);
           
        jmlmahkota.setEnabled(false);
       jmlpangrumat.setEnabled(false);
       jmlpangsi.setEnabled(false);
       jmlperang.setEnabled(false);
       jmlpisang.setEnabled(false);
       jmlpusaka.setEnabled(false);
       jmlrumah.setEnabled(false);

       jmlmahkota.setEnabled(false);
       jmlpangrumat.setEnabled(false);
       jmlpangsi.setEnabled(false);
       jmlperang.setEnabled(false);
       jmlpisang.setEnabled(false);
       jmlpusaka.setEnabled(false);
       jmlrumah.setEnabled(false);

       jButton15.setEnabled(false);
       jButton16.setEnabled(false);
       jButton17.setEnabled(false);
       jButton18.setEnabled(false);
       jButton19.setEnabled(false);
       jButton20.setEnabled(false);
       jButton21.setEnabled(false);
       jButton43.setEnabled(false);
       jButton44.setEnabled(false);
       jButton45.setEnabled(false);
       jButton46.setEnabled(false);
       jButton47.setEnabled(false);
       jButton48.setEnabled(false);
       jButton49.setEnabled(false); 
       produk price = new produk(); 
        listTransaksi.add(" \t\t Meuli Point of Sale"
            + "\n\t\t Transaction Summary"
            + "\n====================================================="
            + "\nJumlah\t\t Nama Barang\t\t Harga");
       
        
         if(Integer.parseInt(jmlmahkota.getText())> 0){
        totalHarga(price.getHargaMahkota()*Integer.parseInt(jmlmahkota.getText()));
        listTransaksi.add(jmlmahkota.getText() +"\t\t Mahkota \t\t Rp. " + price.getHargaMahkota()*Integer.parseInt(jmlmahkota.getText()));
    }
    if(Integer.parseInt(jmlpangrumat.getText())> 0){
        totalHarga(price.getHargaPangrumat()*Integer.parseInt(jmlpangrumat.getText()));
        listTransaksi.add(jmlpangrumat.getText() +"\t\t Pangrumat \t\t Rp. " + price.getHargaPangrumat()*Integer.parseInt(jmlpangrumat.getText()));
    }
    if(Integer.parseInt(jmlpangsi.getText())> 0){
        totalHarga(price.getHargaPangsi()*Integer.parseInt(jmlpangsi.getText()));
        listTransaksi.add(jmlpangsi.getText() +"\t\t Pangsi \t\t Rp. " + price.getHargaPangsi()*Integer.parseInt(jmlpangsi.getText()));
    }
    if(Integer.parseInt(jmlperang.getText())> 0){
        totalHarga(price.getHargaPerang()*Integer.parseInt(jmlperang.getText()));
        listTransaksi.add(jmlperang.getText() +"\t\t Perang \t\t Rp. " + price.getHargaPerang()*Integer.parseInt(jmlperang.getText()));
    }
    if(Integer.parseInt(jmlpisang.getText())> 0){
        totalHarga(price.getHargaPisang()*Integer.parseInt(jmlpisang.getText()));
        listTransaksi.add(jmlpisang.getText() +"\t\t Pisang \t\t Rp. " + price.getHargaPisang()*Integer.parseInt(jmlpisang.getText()));
    }
    if(Integer.parseInt(jmlpusaka.getText())> 0){
        totalHarga(price.getHargaPustaka()*Integer.parseInt(jmlpusaka.getText()));
        listTransaksi.add(jmlpusaka.getText() +"\t\t Pusaka \t\t Rp. " + price.getHargaPustaka()*Integer.parseInt(jmlpusaka.getText()));
    }
    if(Integer.parseInt(jmlrumah.getText())> 0){
        totalHarga(price.getHargaRumah()*Integer.parseInt(jmlrumah.getText()));
        listTransaksi.add(jmlrumah.getText() +"\t\t Rumah \t\t\t Rp. " + price.getHargaRumah()*Integer.parseInt(jmlrumah.getText()));
    }
    
     transaksi = String.join("\n", listTransaksi);
        txtkonfirm.append(transaksi);
        txtTotalHarga.setText(Integer.toString(getTotalHarga()));
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
  listTransaksi.clear();
        resetAll();     
transaksi = "";
jButton12.setEnabled(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
    jmlmahkota.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlmahkota.getText().equals(null)){
                             jmlmahkota.setText("0");
                         }
                         if (Integer.parseInt(jmlmahkota.getText()) > obj.getStockMahkota()){
                        
                         jmlmahkota.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlmahkota.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlmahkota.setText(Integer.toString(Integer.parseInt(jmlmahkota.getText()) + 1));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        if(Integer.parseInt(jmlmahkota.getText())>0){
            jmlmahkota.setText(Integer.toString(Integer.parseInt(jmlmahkota.getText()) -1));
        }
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
     if(Integer.parseInt(jmlpangrumat.getText())>0){
            jmlpangrumat.setText(Integer.toString(Integer.parseInt(jmlpangrumat.getText()) -1));
        }
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
       if(Integer.parseInt(jmlpangsi.getText())>0){
            jmlpangsi.setText(Integer.toString(Integer.parseInt(jmlpangsi.getText()) -1));
        }
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
     if(Integer.parseInt(jmlperang.getText())>0){
            jmlperang.setText(Integer.toString(Integer.parseInt(jmlperang.getText()) -1));
        }
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
     jmlpisang.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlpisang.getText().equals(null)){
                             jmlpisang.setText("0");
                         }
                         if (Integer.parseInt(jmlpisang.getText()) > obj.getStockPisang()){
                        
                         jmlpisang.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlpisang.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlpisang.setText(Integer.toString(Integer.parseInt(jmlpisang.getText()) + 1));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
            if(Integer.parseInt(jmlpisang.getText())>0){
            jmlpisang.setText(Integer.toString(Integer.parseInt(jmlpisang.getText()) -1));
        }
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
       if(Integer.parseInt(jmlpusaka.getText())>0){
            jmlpusaka.setText(Integer.toString(Integer.parseInt(jmlpusaka.getText()) -1));
        }
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
         if(Integer.parseInt(jmlrumah.getText())>0){
            jmlrumah.setText(Integer.toString(Integer.parseInt(jmlrumah.getText()) -1));
        }
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      jmlpangrumat.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlpangrumat.getText().equals(null)){
                             jmlpangrumat.setText("0");
                         }
                         if (Integer.parseInt(jmlpangrumat.getText()) > obj.getStockPangrumat()){
                        
                         jmlpangrumat.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlpangrumat.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlpangrumat.setText(Integer.toString(Integer.parseInt(jmlpangrumat.getText()) + 1));
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
      jmlpangsi.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlpangsi.getText().equals(null)){
                             jmlpangsi.setText("0");
                         }
                         if (Integer.parseInt(jmlpangsi.getText()) > obj.getStockPangsi()){
                        
                         jmlpangsi.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlpangsi.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlpangsi.setText(Integer.toString(Integer.parseInt(jmlpangsi.getText()) + 1));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       jmlperang.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlperang.getText().equals(null)){
                             jmlperang.setText("0");
                         }
                         if (Integer.parseInt(jmlperang.getText()) > obj.getStockPerang()){
                        
                         jmlperang.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlperang.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlperang.setText(Integer.toString(Integer.parseInt(jmlperang.getText()) + 1));
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
      jmlpusaka.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlpusaka.getText().equals(null)){
                             jmlpusaka.setText("0");
                         }
                         if (Integer.parseInt(jmlpusaka.getText()) > obj.getStockPustaka()){
                        
                         jmlpusaka.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlpusaka.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlpusaka.setText(Integer.toString(Integer.parseInt(jmlpusaka.getText()) + 1));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
     jmlrumah.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlrumah.getText().equals(null)){
                             jmlrumah.setText("0");
                         }
                         if (Integer.parseInt(jmlrumah.getText()) > obj.getStockRumah()){
                        
                         jmlrumah.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlrumah.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlrumah.setText(Integer.toString(Integer.parseInt(jmlrumah.getText()) + 1));
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       alert1.showMessageDialog(null, "Transaksi Pemesanan Stock Berhasil!", "Berhasil!", alert1.INFORMATION_MESSAGE);
        pembelian obj = new pembelian();
        obj.setTotalPengeluaran(obj.getTotalPengeluaran()+Integer.parseInt(txtTotalHarga.getText()));
        obj.listPembelianDistributorC.add(transaksi);
        dashboard pw = new dashboard();
        pw.totalbeli += Integer.parseInt(txtTotalHarga.getText());
        tambahStock();
        jButton12.setEnabled(false);
        mulaiTransaksi();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(distributorCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(distributorCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(distributorCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(distributorCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new distributorCFrame().setVisible(true);
            }
        });
        
       
    }
    
      public void setHarga(){
        distributorC obj = new distributorC();
        lblhargamahkota.setText("Rp. " + obj.getDistMahkota());
        lblhargapangrumat.setText("Rp. " + obj.getDistPangrumat());
        lblhargapangsi.setText("Rp. " + obj.getDistPangsi());
        lblhargaperang.setText("Rp. " + obj.getDistPerang());
        lblhargapisang.setText("Rp. " + obj.getDistPisang());
        lblhargapusaka.setText("Rp. " + obj.getDistPustaka());
        lblhargarumah.setText("Rp. "+ obj.getDistRumah());
        
    }
    
    public void tambahStock(){
         produk obj = new produk();
        
       
obj.setStockMahkota(obj.getStockMahkota()+Integer.parseInt(jmlmahkota.getText()));
obj.setStockPangrumat(obj.getStockPangrumat()+Integer.parseInt(jmlpangrumat.getText()));
obj.setStockPangsi(obj.getStockPangsi()+Integer.parseInt(jmlpangsi.getText()));
obj.setStockPerang(obj.getStockPerang()+Integer.parseInt(jmlperang.getText()));
obj.setStockPisang(obj.getStockPisang()+Integer.parseInt(jmlpisang.getText()));
obj.setStockPustaka(obj.getStockPustaka()+Integer.parseInt(jmlpusaka.getText()));
obj.setStockRumah(obj.getStockRumah()+Integer.parseInt(jmlrumah.getText()));
    }
    
    public void mulaiTransaksi(){
         produk obj = new produk();
         lblstockmahkota.setText(Integer.toString(obj.getStockMahkota()));
    lblstockpangrumat.setText(Integer.toString(obj.getStockPangrumat()));
    lblstockpangsi.setText(Integer.toString(obj.getStockPangsi()));
    lblstockperang.setText(Integer.toString(obj.getStockPerang()));
    lblstockpisang.setText(Integer.toString(obj.getStockPisang()));
    lblstockpusaka.setText(Integer.toString(obj.getStockPustaka()));
    lblstockrumah.setText(Integer.toString(obj.getStockRumah()));
    }
    
    public void resetAll(){
        txtTotalHarga.setText("");
        txtkonfirm.setText("");
        jButton13.setEnabled(true);
        jButton12.setEnabled(true);
        jmlmahkota.setEnabled(true);
       jmlpangrumat.setEnabled(true);
       jmlpangsi.setEnabled(true);
       jmlperang.setEnabled(true);
       jmlpisang.setEnabled(true);
       jmlpusaka.setEnabled(true);
       jmlrumah.setEnabled(true);

       jmlmahkota.setText("0");
       jmlpangrumat.setText("0");
       jmlpangsi.setText("0");
       jmlperang.setText("0");
       jmlpisang.setText("0");
       jmlpusaka.setText("0");
       jmlrumah.setText("0");
        
       jButton15.setEnabled(true);
       jButton16.setEnabled(true);
       jButton17.setEnabled(true);
       jButton18.setEnabled(true);
       jButton19.setEnabled(true);
       jButton20.setEnabled(true);
       jButton21.setEnabled(true);
       jButton43.setEnabled(true);
       jButton44.setEnabled(true);
       jButton45.setEnabled(true);
       jButton46.setEnabled(true);
       jButton47.setEnabled(true);
       jButton48.setEnabled(true);
       jButton49.setEnabled(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlmahkota;
    private javax.swing.JTextField jmlpangrumat;
    private javax.swing.JTextField jmlpangsi;
    private javax.swing.JTextField jmlperang;
    private javax.swing.JTextField jmlpisang;
    private javax.swing.JTextField jmlpusaka;
    private javax.swing.JTextField jmlrumah;
    private javax.swing.JLabel lblhargamahkota;
    private javax.swing.JLabel lblhargapangrumat;
    private javax.swing.JLabel lblhargapangsi;
    private javax.swing.JLabel lblhargaperang;
    private javax.swing.JLabel lblhargapisang;
    private javax.swing.JLabel lblhargapusaka;
    private javax.swing.JLabel lblhargarumah;
    private javax.swing.JLabel lblstockmahkota;
    private javax.swing.JLabel lblstockpangrumat;
    private javax.swing.JLabel lblstockpangsi;
    private javax.swing.JLabel lblstockperang;
    private javax.swing.JLabel lblstockpisang;
    private javax.swing.JLabel lblstockpusaka;
    private javax.swing.JLabel lblstockrumah;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextArea txtkonfirm;
    // End of variables declaration//GEN-END:variables
}
