/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import laporan.dashboard;
import laporan.pembelian;
import manageproduk.produk;
import meuli.distributor.distributorA;
import static meuli.distributor.distributorAFrame.transaksi;
/**
 *
 * @author thero
 */
public class distributorBFrame extends javax.swing.JFrame {
  public ArrayList<String> listTransaksi = new ArrayList<String>();
    private int harga = 0;
    public String transaksi;

    /**
     * Creates new form distributorAFrame
     */
    public distributorBFrame() {
       initComponents();

        distributorB obj = new distributorB();
        lblhargacelengan.setText("Rp. " + obj.getDistCelengan());
        lblhargaiket.setText("Rp. " +obj.getDistIket());
        lblhargakamus.setText("Rp. "+ obj.getDistKamus());
        lblhargakaos.setText("Rp. " + obj.getDistKaos());
        lblhargakecapi.setText("Rp. " + obj.getDistKecapi());
        lblhargakopi.setText("Rp. " + obj.getDistKopi());
        lblhargaliwet.setText("Rp. " + obj.getDistLiwet());
       jButton12.setEnabled(false);
    }

    
    public void totalHarga(int x){
        harga+=x;
    }
    public int getTotalHarga(){
        return harga;
    }
    
    public void resetHarga(){
        harga = 0;
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        lblstockcelengan = new javax.swing.JLabel();
        lblhargacelengan = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        lblstockiket = new javax.swing.JLabel();
        lblhargaiket = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        lblstockkamus = new javax.swing.JLabel();
        lblhargakamus = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        lblstockkaos = new javax.swing.JLabel();
        lblhargakaos = new javax.swing.JLabel();
        lblstockkecapi = new javax.swing.JLabel();
        lblhargakecapi = new javax.swing.JLabel();
        lblstockkopi = new javax.swing.JLabel();
        lblhargakopi = new javax.swing.JLabel();
        jmlliwet = new javax.swing.JTextField();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jmlkopi = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jmlkecapi = new javax.swing.JTextField();
        jButton39 = new javax.swing.JButton();
        jmlkaos = new javax.swing.JTextField();
        jButton40 = new javax.swing.JButton();
        jmlkamus = new javax.swing.JTextField();
        jButton41 = new javax.swing.JButton();
        jmliket = new javax.swing.JTextField();
        jButton42 = new javax.swing.JButton();
        jmlcelengan = new javax.swing.JTextField();
        lblstockliwet = new javax.swing.JLabel();
        lblhargaliwet = new javax.swing.JLabel();
        alert1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtkonfirm = new javax.swing.JTextArea();
        txtTotalHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(null);

        jButton11.setText("RESET");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(480, 620, 130, 60);

        jButton12.setText("PESAN STOCK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(480, 350, 130, 140);

        jButton13.setText("TOTAL");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(480, 280, 130, 60);

        jButton14.setText("BACK");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(40, 60, 90, 50);

        jLabel3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("DISTRIBUTOR   B");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 60, 290, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Celengan");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(30, 110, 100, 30);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/celengan1600.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(30, 140, 130, 100);

        lblstockcelengan.setText("5");
        getContentPane().add(lblstockcelengan);
        lblstockcelengan.setBounds(140, 120, 10, 20);

        lblhargacelengan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargacelengan.setText("Rp. 25.000");
        getContentPane().add(lblhargacelengan);
        lblhargacelengan.setBounds(110, 240, 60, 20);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/iketMaung60000.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(170, 140, 130, 100);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Iket");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(170, 110, 120, 30);

        lblstockiket.setText("5");
        getContentPane().add(lblstockiket);
        lblstockiket.setBounds(290, 120, 10, 20);

        lblhargaiket.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaiket.setText("Rp. 25.000");
        getContentPane().add(lblhargaiket);
        lblhargaiket.setBounds(250, 240, 60, 20);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kamus20000.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(310, 140, 130, 100);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Kamus");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(310, 110, 50, 30);

        lblstockkamus.setText("5");
        getContentPane().add(lblstockkamus);
        lblstockkamus.setBounds(420, 120, 10, 20);

        lblhargakamus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakamus.setText("Rp. 25.000");
        getContentPane().add(lblhargakamus);
        lblhargakamus.setBounds(390, 240, 60, 20);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kaosSunda65000.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(450, 140, 130, 100);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Kaos");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(450, 110, 90, 30);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kecapi350000.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(590, 140, 130, 100);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Kecapi");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(590, 110, 90, 30);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/KopiSundaGulali85000.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(730, 140, 130, 100);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Kopi");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(730, 110, 50, 30);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/liwet19000.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(870, 140, 130, 100);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("Liwet");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(870, 110, 100, 30);

        lblstockkaos.setText("5");
        getContentPane().add(lblstockkaos);
        lblstockkaos.setBounds(570, 120, 10, 20);

        lblhargakaos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakaos.setText("Rp. 25.000");
        getContentPane().add(lblhargakaos);
        lblhargakaos.setBounds(530, 240, 60, 20);

        lblstockkecapi.setText("5");
        getContentPane().add(lblstockkecapi);
        lblstockkecapi.setBounds(700, 120, 10, 20);

        lblhargakecapi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakecapi.setText("Rp. 25.000");
        getContentPane().add(lblhargakecapi);
        lblhargakecapi.setBounds(670, 240, 60, 20);

        lblstockkopi.setText("5");
        getContentPane().add(lblstockkopi);
        lblstockkopi.setBounds(840, 120, 10, 20);

        lblhargakopi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakopi.setText("Rp. 25.000");
        getContentPane().add(lblhargakopi);
        lblhargakopi.setBounds(810, 240, 60, 20);

        jmlliwet.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlliwet.setText("0");
        getContentPane().add(jmlliwet);
        jmlliwet.setBounds(910, 240, 30, 20);

        jButton36.setText("-");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(870, 240, 37, 20);

        jButton37.setText("-");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37);
        jButton37.setBounds(730, 240, 37, 20);

        jmlkopi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkopi.setText("0");
        getContentPane().add(jmlkopi);
        jmlkopi.setBounds(770, 240, 30, 20);

        jButton38.setText("-");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38);
        jButton38.setBounds(590, 240, 37, 20);

        jmlkecapi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkecapi.setText("0");
        getContentPane().add(jmlkecapi);
        jmlkecapi.setBounds(630, 240, 30, 20);

        jButton39.setText("-");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton39);
        jButton39.setBounds(450, 240, 37, 20);

        jmlkaos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkaos.setText("0");
        getContentPane().add(jmlkaos);
        jmlkaos.setBounds(490, 240, 30, 20);

        jButton40.setText("-");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton40);
        jButton40.setBounds(310, 240, 37, 20);

        jmlkamus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkamus.setText("0");
        getContentPane().add(jmlkamus);
        jmlkamus.setBounds(350, 240, 30, 20);

        jButton41.setText("-");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41);
        jButton41.setBounds(170, 240, 37, 20);

        jmliket.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmliket.setText("0");
        getContentPane().add(jmliket);
        jmliket.setBounds(210, 240, 30, 20);

        jButton42.setText("-");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton42);
        jButton42.setBounds(30, 240, 37, 20);

        jmlcelengan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlcelengan.setText("0");
        getContentPane().add(jmlcelengan);
        jmlcelengan.setBounds(70, 240, 30, 20);

        lblstockliwet.setText("5");
        getContentPane().add(lblstockliwet);
        lblstockliwet.setBounds(980, 120, 10, 20);

        lblhargaliwet.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaliwet.setText("Rp. 25.000");
        getContentPane().add(lblhargaliwet);
        lblhargaliwet.setBounds(950, 240, 60, 20);
        getContentPane().add(alert1);
        alert1.setBounds(1480, 440, 262, 90);

        txtkonfirm.setColumns(20);
        txtkonfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonfirm.setRows(5);
        txtkonfirm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(txtkonfirm);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 280, 440, 350);

        txtTotalHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalHarga);
        txtTotalHarga.setBounds(30, 640, 440, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/bgbarang.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 1040, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transbg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-170, -50, 1500, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.setVisible(false);
        new distributorframe().setVisible(true); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // 
        if(jmlcelengan.getText().equals("0") && jmliket.getText().equals("0") && jmlkamus.getText().equals("0") && jmlkaos.getText().equals("0") && jmlkecapi.getText().equals("0") && jmlkopi.getText().equals("0") && jmlliwet.getText().equals("0")){
            alert1.showMessageDialog(null, "Tidak ada Barang yang dipesan!", "Perhatian!!", alert1.ERROR_MESSAGE);
        }else{
       produk price = new produk(); 
       jButton13.setEnabled(false);
       jButton12.setEnabled(true);
        
        jmlcelengan.setEnabled(false);
       jmliket.setEnabled(false);
       jmlkamus.setEnabled(false);
       jmlkaos.setEnabled(false);
       jmlkecapi.setEnabled(false);
       jmlkopi.setEnabled(false);
       jmlliwet.setEnabled(false);

       jButton15.setEnabled(false);
       jButton16.setEnabled(false);
       jButton17.setEnabled(false);
       jButton18.setEnabled(false);
       jButton19.setEnabled(false);
       jButton20.setEnabled(false);
       jButton21.setEnabled(false);
       jButton36.setEnabled(false);
       jButton37.setEnabled(false);
       jButton38.setEnabled(false);
       jButton39.setEnabled(false);
       jButton40.setEnabled(false);
       jButton41.setEnabled(false);
       jButton42.setEnabled(false);
       listTransaksi.add(" \t\t Meuli Point of Sale"
            + "\n\t\t Transaction Summary"
            + "\n====================================================="
            + "\nJumlah\t\t Nama Barang\t\t Harga");
       
       
        if(Integer.parseInt(jmlcelengan.getText())> 0){
        totalHarga(price.getHargaCelengan()*Integer.parseInt(jmlcelengan.getText()));
        listTransaksi.add(jmlcelengan.getText() +"\t\t Celengan \t\t Rp. " + price.getHargaCelengan()*Integer.parseInt(jmlcelengan.getText()));
    }
    if(Integer.parseInt(jmliket.getText())> 0){
        totalHarga(price.getHargaIket()*Integer.parseInt(jmliket.getText()));
        listTransaksi.add(jmliket.getText() +"\t\t Iket \t\t\t Rp. " + price.getHargaIket()*Integer.parseInt(jmliket.getText()));
    }
    if(Integer.parseInt(jmlkamus.getText())> 0){
        totalHarga(price.getHargaKamus()*Integer.parseInt(jmlkamus.getText()));
        listTransaksi.add(jmlkamus.getText() +"\t\t Kamus \t\t\t Rp. " + price.getHargaKamus()*Integer.parseInt(jmlkamus.getText()));
    }
    if(Integer.parseInt(jmlkaos.getText())> 0){
        totalHarga(price.getHargaKaos()*Integer.parseInt(jmlkaos.getText()));
        listTransaksi.add(jmlkaos.getText() +"\t\t Kaos \t\t\t Rp. " + price.getHargaKaos()*Integer.parseInt(jmlkaos.getText()));
    }
    if(Integer.parseInt(jmlkecapi.getText())> 0){
        totalHarga(price.getHargaKecapi()*Integer.parseInt(jmlkecapi.getText()));
        listTransaksi.add(jmlkecapi.getText() +"\t\t Kecapi \t\t Rp. " + price.getHargaKecapi()*Integer.parseInt(jmlkecapi.getText()));
    }
    if(Integer.parseInt(jmlkopi.getText())> 0){
        totalHarga(price.getHargaKopi()*Integer.parseInt(jmlkopi.getText()));
        listTransaksi.add(jmlkopi.getText() +"\t\t Kopi \t\t\t Rp. " + price.getHargaKopi()*Integer.parseInt(jmlkopi.getText()));
    }
    if(Integer.parseInt(jmlliwet.getText())> 0){
        totalHarga(price.getHargaLiwet()*Integer.parseInt(jmlliwet.getText()));
        listTransaksi.add(jmlliwet.getText() +"\t\t Liwet \t\t\t Rp. " + price.getHargaLiwet()*Integer.parseInt(jmlliwet.getText()));
    }
    
      transaksi = String.join("\n", listTransaksi);
        txtkonfirm.append(transaksi);
        txtTotalHarga.setText(Integer.toString(getTotalHarga()));
        
       } 
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      resetAll();
      transaksi = "";
      jButton12.setEnabled(false);
        listTransaksi.clear();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
  jmlcelengan.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlcelengan.getText().equals(null)){
                             jmlcelengan.setText("0");
                         }
                         if (Integer.parseInt(jmlcelengan.getText()) > obj.getStockCelengan()){
                        
                         jmlcelengan.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlcelengan.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlcelengan.setText(Integer.toString(Integer.parseInt(jmlcelengan.getText()) + 1));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jmliket.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmliket.getText().equals(null)){
                             jmliket.setText("0");
                         
                        
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmliket.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmliket.setText(Integer.toString(Integer.parseInt(jmliket.getText()) + 1));
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jmlkamus.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlkamus.getText().equals(null)){
                             jmlkamus.setText("0");
                         }
                         if (Integer.parseInt(jmlkamus.getText()) > obj.getStockKamus()){
                        
                         jmlkamus.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlkamus.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlkamus.setText(Integer.toString(Integer.parseInt(jmlkamus.getText()) + 1));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       jmlkaos.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlkaos.getText().equals(null)){
                             jmlkaos.setText("0");
                         }
                         if (Integer.parseInt(jmlkaos.getText()) > obj.getStockKaos()){
                        
                         jmlkaos.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlkaos.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlkaos.setText(Integer.toString(Integer.parseInt(jmlkaos.getText()) + 1));
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jmlkecapi.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlkecapi.getText().equals(null)){
                             jmlkecapi.setText("0");
                         }
                         if (Integer.parseInt(jmlkecapi.getText()) > obj.getStockKecapi()){
                        
                         jmlkecapi.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlkecapi.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });  
        jmlkecapi.setText(Integer.toString(Integer.parseInt(jmlkecapi.getText()) + 1));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
      jmlkopi.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlkopi.getText().equals(null)){
                             jmlkopi.setText("0");
                         }
                         if (Integer.parseInt(jmlkopi.getText()) > obj.getStockKopi()){
                        
                         jmlkopi.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlkopi.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });   
         jmlkopi.setText(Integer.toString(Integer.parseInt(jmlkopi.getText()) + 1));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
         jmlliwet.getDocument().addDocumentListener(new DocumentListener() {
             public void changedUpdate(DocumentEvent e) {
             }
             public void removeUpdate(DocumentEvent e) {
             }
             public void insertUpdate(DocumentEvent e) {
                 warn();
                 }
        
             public void warn() {
                 Runnable doWarn = new Runnable() {
                     @Override
                     public void run() {
                         try{
                             produk obj = new produk();
                         if(jmlliwet.getText().equals(null)){
                             jmlliwet.setText("0");
                         }
                         if (Integer.parseInt(jmlliwet.getText()) > obj.getStockLiwet()){
                        
                         jmlliwet.setText("0");
                     }  
                             
                         }
                         catch(NumberFormatException e){
                             jmlliwet.setText("0");
                             alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
                             
                         }
                         
                         }};SwingUtilities.invokeLater(doWarn);
                
                 }
         });      
        jmlliwet.setText(Integer.toString(Integer.parseInt(jmlliwet.getText()) + 1));
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        if(Integer.parseInt(jmlcelengan.getText())>0){
            jmlcelengan.setText(Integer.toString(Integer.parseInt(jmlcelengan.getText()) -1));
        }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
            if(Integer.parseInt(jmliket.getText())>0){
            jmliket.setText(Integer.toString(Integer.parseInt(jmliket.getText()) -1));
        }
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
     if(Integer.parseInt(jmlkamus.getText())>0){
            jmlkamus.setText(Integer.toString(Integer.parseInt(jmlkamus.getText()) -1));
        }
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        if(Integer.parseInt(jmlkaos.getText())>0){
            jmlkaos.setText(Integer.toString(Integer.parseInt(jmlkaos.getText()) -1));
        }
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
         if(Integer.parseInt(jmlkecapi.getText())>0){
            jmlkecapi.setText(Integer.toString(Integer.parseInt(jmlkecapi.getText()) -1));
        }
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
          if(Integer.parseInt(jmlkopi.getText())>0){
            jmlkopi.setText(Integer.toString(Integer.parseInt(jmlkopi.getText()) -1));
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
      if(Integer.parseInt(jmlliwet.getText())>0){
            jmlliwet.setText(Integer.toString(Integer.parseInt(jmlliwet.getText()) -1));
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       alert1.showMessageDialog(null, "Transaksi Pemesanan Stock Berhasil!", "Berhasil!", alert1.INFORMATION_MESSAGE);
        pembelian obj = new pembelian();
        obj.setTotalPengeluaran(obj.getTotalPengeluaran()+Integer.parseInt(txtTotalHarga.getText()));
        obj.listPembelianDistributorB.add(transaksi);
        dashboard pw = new dashboard();
        pw.totalbeli += Integer.parseInt(txtTotalHarga.getText());
        tambahStock();
        recordStock();
        jButton12.setEnabled(false);
        mulaiTransaksi();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(distributorBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(distributorBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(distributorBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(distributorBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new distributorBFrame().setVisible(true);
            }
        });
        
       
    }
    
    public void setHarga(){
        distributorB obj = new distributorB();
        lblhargacelengan.setText("Rp. " + obj.getDistCelengan());
        lblhargaiket.setText("Rp. " +obj.getDistIket());
        lblhargakamus.setText("Rp. "+ obj.getDistKamus());
        lblhargakaos.setText("Rp. " + obj.getDistKaos());
        lblhargakecapi.setText("Rp. " + obj.getDistKecapi());
        lblhargakopi.setText("Rp. " + obj.getDistKopi());
        lblhargaliwet.setText("Rp. " + obj.getDistLiwet());
    }
    
    public void tambahStock(){
         produk obj = new produk();
        
       
obj.setStockCelengan(obj.getStockCelengan()-Integer.parseInt(jmlcelengan.getText()));
obj.setStockIket(obj.getStockIket()-Integer.parseInt(jmliket.getText()));
obj.setStockKamus(obj.getStockKamus()-Integer.parseInt(jmlkamus.getText()));
obj.setStockKaos(obj.getStockKaos()-Integer.parseInt(jmlkaos.getText()));
obj.setStockKecapi(obj.getStockKecapi()-Integer.parseInt(jmlkecapi.getText()));
obj.setStockKopi(obj.getStockKopi()-Integer.parseInt(jmlkopi.getText()));
obj.setStockLiwet(obj.getStockLiwet()-Integer.parseInt(jmlliwet.getText()));

    }
    
    public void recordStock(){
     pembelian obj = new pembelian();
        //celengan,iket,kamus,kaos,kecapi,kopi,liwet
    obj.recordCelengan += Integer.parseInt(jmlcelengan.getText());
    obj.recordIket += Integer.parseInt(jmliket.getText());
    obj.recordKamus += Integer.parseInt(jmlkamus.getText());
    obj.recordKaos += Integer.parseInt(jmlkaos.getText());
    obj.recordKecapi += Integer.parseInt(jmlkecapi.getText());
    obj.recordKopi += Integer.parseInt(jmlkopi.getText());
    obj.recordLiwet += Integer.parseInt(jmlliwet.getText());
   
    }
    
    public void mulaiTransaksi(){
         produk obj = new produk();
         lblstockcelengan.setText(Integer.toString(obj.getStockCelengan()));
    lblstockiket.setText(Integer.toString(obj.getStockIket()));
    lblstockkamus.setText(Integer.toString(obj.getStockKamus()));
    lblstockkaos.setText(Integer.toString(obj.getStockKaos()));
    lblstockkecapi.setText(Integer.toString(obj.getStockKecapi()));
    lblstockkopi.setText(Integer.toString(obj.getStockKopi()));
    lblstockliwet.setText(Integer.toString(obj.getStockLiwet()));
    }
    
    public void resetAll(){
        txtTotalHarga.setText("");
        txtkonfirm.setText("");
        jButton13.setEnabled(true);
        jButton12.setEnabled(true);
        
        jmlcelengan.setEnabled(true);
       jmliket.setEnabled(true);
       jmlkamus.setEnabled(true);
       jmlkaos.setEnabled(true);
       jmlkecapi.setEnabled(true);
       jmlkopi.setEnabled(true);
       jmlliwet.setEnabled(true);    

       jmlcelengan.setText("0");
       jmliket.setText("0");
       jmlkamus.setText("0");
       jmlkaos.setText("0");
       jmlkecapi.setText("0");
       jmlkopi.setText("0");
       jmlliwet.setText("0");

       jButton15.setEnabled(true);
       jButton16.setEnabled(true);
       jButton17.setEnabled(true);
       jButton18.setEnabled(true);
       jButton19.setEnabled(true);
       jButton20.setEnabled(true);
       jButton21.setEnabled(true);
       jButton36.setEnabled(true);
       jButton37.setEnabled(true);
       jButton38.setEnabled(true);
       jButton39.setEnabled(true);
       jButton40.setEnabled(true);
       jButton41.setEnabled(true);
       jButton42.setEnabled(true);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlcelengan;
    private javax.swing.JTextField jmliket;
    private javax.swing.JTextField jmlkamus;
    private javax.swing.JTextField jmlkaos;
    private javax.swing.JTextField jmlkecapi;
    private javax.swing.JTextField jmlkopi;
    private javax.swing.JTextField jmlliwet;
    private javax.swing.JLabel lblhargacelengan;
    private javax.swing.JLabel lblhargaiket;
    private javax.swing.JLabel lblhargakamus;
    private javax.swing.JLabel lblhargakaos;
    private javax.swing.JLabel lblhargakecapi;
    private javax.swing.JLabel lblhargakopi;
    private javax.swing.JLabel lblhargaliwet;
    private javax.swing.JLabel lblstockcelengan;
    private javax.swing.JLabel lblstockiket;
    private javax.swing.JLabel lblstockkamus;
    private javax.swing.JLabel lblstockkaos;
    private javax.swing.JLabel lblstockkecapi;
    private javax.swing.JLabel lblstockkopi;
    private javax.swing.JLabel lblstockliwet;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextArea txtkonfirm;
    // End of variables declaration//GEN-END:variables
}
