/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor;

import manageproduk.produk;

/**
 *
 * @author thero
 */
public class ubahHargaDistB extends javax.swing.JFrame {

    /**
     * Creates new form ubahHargaDistA
     */
    public ubahHargaDistB() {
        initComponents();
        distributorB obj = new distributorB();
        lblhargacelengan.setText("Rp. " + obj.getDistCelengan());
        lblhargaiket.setText("Rp. " +obj.getDistIket());
        lblhargakamus.setText("Rp. "+ obj.getDistKamus());
        lblhargakaos.setText("Rp. " + obj.getDistKaos());
        lblhargakecapi.setText("Rp. " + obj.getDistKecapi());
        lblhargakopi.setText("Rp. " + obj.getDistKopi());
        lblhargaliwet.setText("Rp. " + obj.getDistLiwet());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert1 = new javax.swing.JOptionPane();
        lblhargaangklung2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        lblhargacelengan = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        lblhargaiket = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        lblhargakamus = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        lblhargakaos = new javax.swing.JLabel();
        lblhargakecapi = new javax.swing.JLabel();
        lblhargakopi = new javax.swing.JLabel();
        jmlliwet = new javax.swing.JTextField();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jmlkopi = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jmlkecapi = new javax.swing.JTextField();
        jButton39 = new javax.swing.JButton();
        jmlkaos = new javax.swing.JTextField();
        jButton40 = new javax.swing.JButton();
        jmlkamus = new javax.swing.JTextField();
        jButton41 = new javax.swing.JButton();
        jmliket = new javax.swing.JTextField();
        jButton42 = new javax.swing.JButton();
        jmlcelengan = new javax.swing.JTextField();
        lblhargaliwet = new javax.swing.JLabel();
        lblhargaangklung10 = new javax.swing.JLabel();
        lblhargaangklung11 = new javax.swing.JLabel();
        lblhargaangklung12 = new javax.swing.JLabel();
        lblhargaangklung13 = new javax.swing.JLabel();
        lblhargaangklung14 = new javax.swing.JLabel();
        lblhargaangklung15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 750));
        setPreferredSize(new java.awt.Dimension(1100, 750));
        getContentPane().setLayout(null);

        lblhargaangklung2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung2.setText("Harga Lama");
        getContentPane().add(lblhargaangklung2);
        lblhargaangklung2.setBounds(880, 230, 60, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Celengan");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(40, 100, 100, 30);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/celengan1600.png"))); // NOI18N
        getContentPane().add(jButton15);
        jButton15.setBounds(40, 130, 130, 100);

        lblhargacelengan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargacelengan.setText("Rp. 25.000");
        getContentPane().add(lblhargacelengan);
        lblhargacelengan.setBounds(110, 230, 60, 20);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/iketMaung60000.png"))); // NOI18N
        getContentPane().add(jButton16);
        jButton16.setBounds(180, 130, 130, 100);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Iket");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(180, 100, 120, 30);

        lblhargaiket.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaiket.setText("Rp. 25.000");
        getContentPane().add(lblhargaiket);
        lblhargaiket.setBounds(250, 230, 60, 20);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kamus20000.png"))); // NOI18N
        getContentPane().add(jButton17);
        jButton17.setBounds(320, 130, 130, 100);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Kamus");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(320, 100, 50, 30);

        lblhargakamus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakamus.setText("Rp. 25.000");
        getContentPane().add(lblhargakamus);
        lblhargakamus.setBounds(390, 230, 60, 20);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kaosSunda65000.png"))); // NOI18N
        getContentPane().add(jButton18);
        jButton18.setBounds(460, 130, 130, 100);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Kaos");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(460, 100, 90, 30);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/kecapi350000.png"))); // NOI18N
        getContentPane().add(jButton19);
        jButton19.setBounds(600, 130, 130, 100);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Kecapi");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(600, 100, 90, 30);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/KopiSundaGulali85000.png"))); // NOI18N
        getContentPane().add(jButton20);
        jButton20.setBounds(740, 130, 130, 100);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Kopi");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(740, 100, 50, 30);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/liwet19000.png"))); // NOI18N
        getContentPane().add(jButton21);
        jButton21.setBounds(880, 130, 130, 100);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("Liwet");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(880, 100, 100, 30);

        lblhargakaos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakaos.setText("Rp. 25.000");
        getContentPane().add(lblhargakaos);
        lblhargakaos.setBounds(530, 230, 60, 20);

        lblhargakecapi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakecapi.setText("Rp. 25.000");
        getContentPane().add(lblhargakecapi);
        lblhargakecapi.setBounds(670, 230, 60, 20);

        lblhargakopi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargakopi.setText("Rp. 25.000");
        getContentPane().add(lblhargakopi);
        lblhargakopi.setBounds(810, 230, 60, 20);

        jmlliwet.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlliwet.setText("0");
        getContentPane().add(jmlliwet);
        jmlliwet.setBounds(880, 250, 130, 20);

        jButton36.setText("Ubah");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(880, 280, 130, 20);

        jButton37.setText("Ubah");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37);
        jButton37.setBounds(740, 280, 130, 20);

        jmlkopi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkopi.setText("0");
        getContentPane().add(jmlkopi);
        jmlkopi.setBounds(740, 250, 130, 20);

        jButton38.setText("Ubah");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38);
        jButton38.setBounds(600, 280, 130, 20);

        jmlkecapi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkecapi.setText("0");
        getContentPane().add(jmlkecapi);
        jmlkecapi.setBounds(600, 250, 130, 20);

        jButton39.setText("Ubah");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton39);
        jButton39.setBounds(460, 280, 130, 20);

        jmlkaos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkaos.setText("0");
        getContentPane().add(jmlkaos);
        jmlkaos.setBounds(460, 250, 130, 20);

        jButton40.setText("Ubah");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton40);
        jButton40.setBounds(320, 280, 130, 20);

        jmlkamus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlkamus.setText("0");
        getContentPane().add(jmlkamus);
        jmlkamus.setBounds(320, 250, 130, 20);

        jButton41.setText("Ubah");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41);
        jButton41.setBounds(180, 280, 130, 20);

        jmliket.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmliket.setText("0");
        getContentPane().add(jmliket);
        jmliket.setBounds(180, 250, 130, 20);

        jButton42.setText("Ubah");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton42);
        jButton42.setBounds(40, 280, 130, 20);

        jmlcelengan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlcelengan.setText("0");
        getContentPane().add(jmlcelengan);
        jmlcelengan.setBounds(40, 250, 130, 20);

        lblhargaliwet.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaliwet.setText("Rp. 25.000");
        getContentPane().add(lblhargaliwet);
        lblhargaliwet.setBounds(950, 230, 60, 20);

        lblhargaangklung10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung10.setText("Harga Lama");
        getContentPane().add(lblhargaangklung10);
        lblhargaangklung10.setBounds(180, 230, 60, 20);

        lblhargaangklung11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung11.setText("Harga Lama");
        getContentPane().add(lblhargaangklung11);
        lblhargaangklung11.setBounds(320, 230, 60, 20);

        lblhargaangklung12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung12.setText("Harga Lama");
        getContentPane().add(lblhargaangklung12);
        lblhargaangklung12.setBounds(460, 230, 60, 20);

        lblhargaangklung13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung13.setText("Harga Lama");
        getContentPane().add(lblhargaangklung13);
        lblhargaangklung13.setBounds(600, 230, 60, 20);

        lblhargaangklung14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung14.setText("Harga Lama");
        getContentPane().add(lblhargaangklung14);
        lblhargaangklung14.setBounds(740, 230, 60, 20);

        lblhargaangklung15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung15.setText("Harga Lama");
        getContentPane().add(lblhargaangklung15);
        lblhargaangklung15.setBounds(40, 230, 60, 20);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 40, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transbg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-240, -40, 1500, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        distributorB obj = new distributorB();
        try{
            if(Integer.parseInt(jmlliwet.getText())>0){
                obj.setDistLiwet(Integer.parseInt(jmlliwet.getText()));
                lblhargaliwet.setText("Rp. " + obj.getDistLiwet());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
                                          
        distributorB obj = new distributorB();
        try{
            if(Integer.parseInt(jmlkopi.getText())>0){
                obj.setDistKopi(Integer.parseInt(jmlkopi.getText()));
                lblhargakopi.setText("Rp. " + obj.getDistKopi());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
         distributorB obj = new distributorB();
        try{
            if(Integer.parseInt(jmlkecapi.getText())>0){
                obj.setDistKecapi(Integer.parseInt(jmlkecapi.getText()));
                lblhargakecapi.setText("Rp. " + obj.getDistKecapi());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed

        distributorB obj = new distributorB();
        try{
            if(Integer.parseInt(jmlkaos.getText())>0){
                obj.setDistKaos(Integer.parseInt(jmlkaos.getText()));
                lblhargakaos.setText("Rp. " + obj.getDistKaos());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed

        distributorB obj = new distributorB();
        try{
            if(Integer.parseInt(jmlkamus.getText())>0){
                obj.setDistKamus(Integer.parseInt(jmlkamus.getText()));
                lblhargakamus.setText("Rp. " + obj.getDistKamus());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
                                         
        distributorB obj = new distributorB();
        try{
            if(Integer.parseInt(jmliket.getText())>0){
                obj.setDistIket(Integer.parseInt(jmliket.getText()));
                lblhargaiket.setText("Rp. " + obj.getDistIket());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
                                          
        distributorB obj = new distributorB();
        try{
            if(Integer.parseInt(jmlcelengan.getText())>0){
                obj.setDistCelengan(Integer.parseInt(jmlcelengan.getText()));
                lblhargacelengan.setText("Rp. " + obj.getDistCelengan());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new hargadistributorframe().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahHargaDistB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JTextField jmlcelengan;
    private javax.swing.JTextField jmliket;
    private javax.swing.JTextField jmlkamus;
    private javax.swing.JTextField jmlkaos;
    private javax.swing.JTextField jmlkecapi;
    private javax.swing.JTextField jmlkopi;
    private javax.swing.JTextField jmlliwet;
    private javax.swing.JLabel lblhargaangklung10;
    private javax.swing.JLabel lblhargaangklung11;
    private javax.swing.JLabel lblhargaangklung12;
    private javax.swing.JLabel lblhargaangklung13;
    private javax.swing.JLabel lblhargaangklung14;
    private javax.swing.JLabel lblhargaangklung15;
    private javax.swing.JLabel lblhargaangklung2;
    private javax.swing.JLabel lblhargacelengan;
    private javax.swing.JLabel lblhargaiket;
    private javax.swing.JLabel lblhargakamus;
    private javax.swing.JLabel lblhargakaos;
    private javax.swing.JLabel lblhargakecapi;
    private javax.swing.JLabel lblhargakopi;
    private javax.swing.JLabel lblhargaliwet;
    // End of variables declaration//GEN-END:variables
}
