/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor;

import manageproduk.produk;

/**
 *
 * @author thero
 */
public class ubahHargaDistD extends javax.swing.JFrame {

    /**
     * Creates new form ubahHargaDistA
     */
    public ubahHargaDistD() {
        initComponents();
        distributorD obj = new distributorD();
        lblhargasasakala.setText("Rp. " +obj.getDistSasakala());
        lblhargasiger.setText("Rp. " + obj.getDistSiger());
        lblhargasimpay.setText("Rp. " + obj.getDistSimpay());
        lblhargasuling.setText("Rp. " + obj.getDistSuling());
        lblhargatales.setText("Rp. " + obj.getDistTales());
        lblhargatotopong.setText("Rp. " + obj.getDistTotopong());
        lblhargaudeng.setText("Rp. " + obj.getDistUdeng());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert1 = new javax.swing.JOptionPane();
        lblhargaangklung16 = new javax.swing.JLabel();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        lblhargasasakala = new javax.swing.JLabel();
        lblhargasiger = new javax.swing.JLabel();
        lblhargasimpay = new javax.swing.JLabel();
        lblhargasuling = new javax.swing.JLabel();
        lblhargatales = new javax.swing.JLabel();
        lblhargatotopong = new javax.swing.JLabel();
        lblhargaudeng = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jmludeng = new javax.swing.JTextField();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jmltotopong = new javax.swing.JTextField();
        jButton59 = new javax.swing.JButton();
        jmltales = new javax.swing.JTextField();
        jButton60 = new javax.swing.JButton();
        jmlsuling = new javax.swing.JTextField();
        jButton61 = new javax.swing.JButton();
        jmlsimpay = new javax.swing.JTextField();
        jButton62 = new javax.swing.JButton();
        jmlsiger = new javax.swing.JTextField();
        jButton63 = new javax.swing.JButton();
        jmlsasakala = new javax.swing.JTextField();
        lblhargaangklung23 = new javax.swing.JLabel();
        lblhargaangklung24 = new javax.swing.JLabel();
        lblhargaangklung25 = new javax.swing.JLabel();
        lblhargaangklung26 = new javax.swing.JLabel();
        lblhargaangklung27 = new javax.swing.JLabel();
        lblhargaangklung28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 750));
        getContentPane().setLayout(null);

        lblhargaangklung16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung16.setText("Harga Lama");
        getContentPane().add(lblhargaangklung16);
        lblhargaangklung16.setBounds(900, 240, 60, 20);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/sasakalaSunda17000.png"))); // NOI18N
        getContentPane().add(jButton50);
        jButton50.setBounds(60, 140, 130, 100);

        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/SigerAnak55000.png"))); // NOI18N
        getContentPane().add(jButton51);
        jButton51.setBounds(200, 140, 130, 100);

        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/SimpayBasaSunda98000.png"))); // NOI18N
        getContentPane().add(jButton52);
        jButton52.setBounds(340, 140, 130, 100);

        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/suling10000.png"))); // NOI18N
        getContentPane().add(jButton53);
        jButton53.setBounds(480, 140, 130, 100);

        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/tales15000.png"))); // NOI18N
        getContentPane().add(jButton54);
        jButton54.setBounds(620, 140, 130, 100);

        jButton55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/totopong12000.png"))); // NOI18N
        getContentPane().add(jButton55);
        jButton55.setBounds(760, 140, 130, 100);

        jButton56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/udeng75000.png"))); // NOI18N
        getContentPane().add(jButton56);
        jButton56.setBounds(900, 140, 130, 100);

        lblhargasasakala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasasakala.setText("Rp. 25.000");
        getContentPane().add(lblhargasasakala);
        lblhargasasakala.setBounds(130, 240, 60, 20);

        lblhargasiger.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasiger.setText("Rp. 25.000");
        getContentPane().add(lblhargasiger);
        lblhargasiger.setBounds(270, 240, 60, 20);

        lblhargasimpay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasimpay.setText("Rp. 25.000");
        getContentPane().add(lblhargasimpay);
        lblhargasimpay.setBounds(410, 240, 60, 20);

        lblhargasuling.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargasuling.setText("Rp. 25.000");
        getContentPane().add(lblhargasuling);
        lblhargasuling.setBounds(550, 240, 60, 20);

        lblhargatales.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargatales.setText("Rp. 25.000");
        getContentPane().add(lblhargatales);
        lblhargatales.setBounds(690, 240, 60, 20);

        lblhargatotopong.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargatotopong.setText("Rp. 25.000");
        getContentPane().add(lblhargatotopong);
        lblhargatotopong.setBounds(830, 240, 60, 20);

        lblhargaudeng.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaudeng.setText("Rp. 25.000");
        getContentPane().add(lblhargaudeng);
        lblhargaudeng.setBounds(970, 240, 60, 20);

        jLabel110.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel110.setText("Udeng");
        getContentPane().add(jLabel110);
        jLabel110.setBounds(900, 110, 130, 30);

        jLabel111.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel111.setText("Totopong");
        getContentPane().add(jLabel111);
        jLabel111.setBounds(760, 110, 70, 30);

        jLabel112.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel112.setText("Tales");
        getContentPane().add(jLabel112);
        jLabel112.setBounds(620, 110, 110, 30);

        jLabel113.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel113.setText("Suling");
        getContentPane().add(jLabel113);
        jLabel113.setBounds(480, 110, 80, 30);

        jLabel114.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel114.setText("Simpay");
        getContentPane().add(jLabel114);
        jLabel114.setBounds(340, 110, 150, 30);

        jLabel115.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel115.setText("Siger");
        getContentPane().add(jLabel115);
        jLabel115.setBounds(200, 110, 50, 30);

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel116.setText("Sasakala");
        getContentPane().add(jLabel116);
        jLabel116.setBounds(60, 110, 110, 30);

        jmludeng.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmludeng.setText("0");
        getContentPane().add(jmludeng);
        jmludeng.setBounds(900, 260, 130, 20);

        jButton57.setText("Ubah");
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton57);
        jButton57.setBounds(900, 290, 130, 20);

        jButton58.setText("Ubah");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton58);
        jButton58.setBounds(760, 290, 130, 20);

        jmltotopong.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmltotopong.setText("0");
        getContentPane().add(jmltotopong);
        jmltotopong.setBounds(760, 260, 130, 20);

        jButton59.setText("Ubah");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton59);
        jButton59.setBounds(620, 290, 130, 20);

        jmltales.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmltales.setText("0");
        getContentPane().add(jmltales);
        jmltales.setBounds(620, 260, 130, 20);

        jButton60.setText("Ubah");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton60);
        jButton60.setBounds(480, 290, 130, 20);

        jmlsuling.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsuling.setText("0");
        getContentPane().add(jmlsuling);
        jmlsuling.setBounds(480, 260, 130, 20);

        jButton61.setText("Ubah");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton61);
        jButton61.setBounds(340, 290, 130, 20);

        jmlsimpay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsimpay.setText("0");
        getContentPane().add(jmlsimpay);
        jmlsimpay.setBounds(340, 260, 130, 20);

        jButton62.setText("Ubah");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton62);
        jButton62.setBounds(200, 290, 130, 20);

        jmlsiger.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsiger.setText("0");
        getContentPane().add(jmlsiger);
        jmlsiger.setBounds(200, 260, 130, 20);

        jButton63.setText("Ubah");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton63);
        jButton63.setBounds(60, 290, 130, 20);

        jmlsasakala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlsasakala.setText("0");
        getContentPane().add(jmlsasakala);
        jmlsasakala.setBounds(60, 260, 130, 20);

        lblhargaangklung23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung23.setText("Harga Lama");
        getContentPane().add(lblhargaangklung23);
        lblhargaangklung23.setBounds(60, 240, 60, 20);

        lblhargaangklung24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung24.setText("Harga Lama");
        getContentPane().add(lblhargaangklung24);
        lblhargaangklung24.setBounds(200, 240, 60, 20);

        lblhargaangklung25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung25.setText("Harga Lama");
        getContentPane().add(lblhargaangklung25);
        lblhargaangklung25.setBounds(340, 240, 60, 20);

        lblhargaangklung26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung26.setText("Harga Lama");
        getContentPane().add(lblhargaangklung26);
        lblhargaangklung26.setBounds(480, 240, 60, 20);

        lblhargaangklung27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung27.setText("Harga Lama");
        getContentPane().add(lblhargaangklung27);
        lblhargaangklung27.setBounds(620, 240, 60, 20);

        lblhargaangklung28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung28.setText("Harga Lama");
        getContentPane().add(lblhargaangklung28);
        lblhargaangklung28.setBounds(760, 240, 60, 20);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 40, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transbg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-170, -50, 1500, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        // TODO add your handling code here:
        distributorD obj = new distributorD();
        try{
            if(Integer.parseInt(jmludeng.getText())>0){
                obj.setDistUdeng(Integer.parseInt(jmludeng.getText()));
                lblhargaudeng.setText("Rp. " + obj.getDistUdeng());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
       distributorD obj = new distributorD();
        try{
            if(Integer.parseInt(jmltotopong.getText())>0){
                obj.setDistTotopong(Integer.parseInt(jmltotopong.getText()));
                lblhargatotopong.setText("Rp. " + obj.getDistTotopong());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        distributorD obj = new distributorD();
        try{
            if(Integer.parseInt(jmltales.getText())>0){
                obj.setDistTales(Integer.parseInt(jmltales.getText()));
                lblhargatales.setText("Rp. " + obj.getDistTales());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
        distributorD obj = new distributorD();
        try{
            if(Integer.parseInt(jmlsuling.getText())>0){
                obj.setDistSuling(Integer.parseInt(jmlsuling.getText()));
                lblhargasuling.setText("Rp. " + obj.getDistSuling());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        distributorD obj = new distributorD();
        try{
            if(Integer.parseInt(jmlsimpay.getText())>0){
                obj.setDistSimpay(Integer.parseInt(jmlsimpay.getText()));
                lblhargasimpay.setText("Rp. " + obj.getDistSimpay());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
       distributorD obj = new distributorD();
        try{
            if(Integer.parseInt(jmlsiger.getText())>0){
                obj.setDistSiger(Integer.parseInt(jmlsiger.getText()));
                lblhargasiger.setText("Rp. " + obj.getDistSiger());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
       distributorD obj = new distributorD();
        try{
            if(Integer.parseInt(jmlsasakala.getText())>0){
                obj.setDistSasakala(Integer.parseInt(jmlsasakala.getText()));
                lblhargasasakala.setText("Rp. " + obj.getDistSasakala());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new hargadistributorframe().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahHargaDistD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JTextField jmlsasakala;
    private javax.swing.JTextField jmlsiger;
    private javax.swing.JTextField jmlsimpay;
    private javax.swing.JTextField jmlsuling;
    private javax.swing.JTextField jmltales;
    private javax.swing.JTextField jmltotopong;
    private javax.swing.JTextField jmludeng;
    private javax.swing.JLabel lblhargaangklung16;
    private javax.swing.JLabel lblhargaangklung23;
    private javax.swing.JLabel lblhargaangklung24;
    private javax.swing.JLabel lblhargaangklung25;
    private javax.swing.JLabel lblhargaangklung26;
    private javax.swing.JLabel lblhargaangklung27;
    private javax.swing.JLabel lblhargaangklung28;
    private javax.swing.JLabel lblhargasasakala;
    private javax.swing.JLabel lblhargasiger;
    private javax.swing.JLabel lblhargasimpay;
    private javax.swing.JLabel lblhargasuling;
    private javax.swing.JLabel lblhargatales;
    private javax.swing.JLabel lblhargatotopong;
    private javax.swing.JLabel lblhargaudeng;
    // End of variables declaration//GEN-END:variables
}
