/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor;

import manageproduk.produk;

/**
 *
 * @author thero
 */
public class ubahHargaDistA extends javax.swing.JFrame {

    /**
     * Creates new form ubahHargaDistA
     */
    public ubahHargaDistA() {
        initComponents();
        
 
        distributorA obj = new distributorA();
        lblhargaangklung.setText("Rp. " + obj.getDistAngklung());
        lblhargabesokap.setText("Rp. " + obj.getDistBesokap());
        lblhargablankon.setText("Rp. " + obj.getDistBlankon());
        lblhargabros.setText("Rp. "+ obj.getDistBros());
        lblhargabukubelajar.setText("Rp. " + obj.getDistBukuBelajar());
        lblhargabukucerita.setText("Rp. " + obj.getDistBukuCerita());
        lblhargabumbu.setText("Rp. " + obj.getDistBumbu());
          /*
         distributorB obj = new distributorB();
        lblhargacelengan.setText("Rp. " + obj.getHargaCelengan());
        lblhargaiket.setText("Rp. " +obj.getHargaIket());
        lblhargakamus.setText("Rp. "+ obj.getHargaKamus());
        lblhargakaos.setText("Rp. " + obj.getHargaKaos());
        lblhargakecapi.setText("Rp. " + obj.getHargaKecapi());
        lblhargakopi.setText("Rp. " + obj.getHargaKopi());
        lblhargaliwet.setText("Rp. " + obj.getHargaLiwet());
        */
         /*
        
        lblhargamahkota.setText("Rp. " + obj.getHargaMahkota());
        lblhargapangrumat.setText("Rp. " + obj.getHargaPangrumat());
        lblhargapangsi.setText("Rp. " + obj.getHargaPangsi());
        lblhargaperang.setText("Rp. " + obj.getHargaPerang());
        lblhargapisang.setText("Rp. " + obj.getHargaPisang());
        lblhargapusaka.setText("Rp. " + obj.getHargaPustaka());
        lblhargarumah.setText("Rp. "+ obj.getHargaRumah());
        */
        /*
        lblhargasasakala.setText("Rp. " +obj.getHargaSasakala());
        lblhargasiger.setText("Rp. " + obj.getHargaSiger());
        lblhargasimpay.setText("Rp. " + obj.getHargaSimpay());
        lblhargasuling.setText("Rp. " + obj.getHargaSuling());
        lblhargatales.setText("Rp. " + obj.getHargaTales());
        lblhargatotopong.setText("Rp. " + obj.getHargaTotopong());
        lblhargaudeng.setText("Rp. " + obj.getHargaUdeng());
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert1 = new javax.swing.JOptionPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lblhargabukubelajar = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        lblhargabukucerita = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        lblhargabumbu = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jmlbesokap = new javax.swing.JTextField();
        jmlblankon = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jmlbros = new javax.swing.JTextField();
        jmlbukubelajar = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        jmlbukucerita = new javax.swing.JTextField();
        jButton34 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jmlbumbu = new javax.swing.JTextField();
        jButton35 = new javax.swing.JButton();
        jmlangklung = new javax.swing.JTextField();
        lblhargabros = new javax.swing.JLabel();
        lblhargablankon = new javax.swing.JLabel();
        lblhargabesokap = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblhargaangklung222 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblhargaangklung = new javax.swing.JLabel();
        lblhargaangklung3 = new javax.swing.JLabel();
        lblhargaangklung4 = new javax.swing.JLabel();
        lblhargaangklung5 = new javax.swing.JLabel();
        lblhargaangklung6 = new javax.swing.JLabel();
        lblhargaangklung7 = new javax.swing.JLabel();
        lblhargaangklung8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setPreferredSize(new java.awt.Dimension(1000, 750));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/broskujang50000.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 150, 130, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/angklung25000.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 150, 130, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/beskap115000.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 150, 130, 100);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/blankonSunda90000.png"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 150, 130, 100);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bukubelajar25000.png"))); // NOI18N
        getContentPane().add(jButton5);
        jButton5.setBounds(590, 150, 130, 100);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Buku Belajar");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(590, 120, 110, 30);

        lblhargabukubelajar.setText("Rp. 25.000");
        getContentPane().add(lblhargabukubelajar);
        lblhargabukubelajar.setBounds(660, 250, 60, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bukucerita25000.png"))); // NOI18N
        getContentPane().add(jButton6);
        jButton6.setBounds(730, 150, 130, 100);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Buku Cerita");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(730, 120, 110, 30);

        lblhargabukucerita.setText("Rp. 25.000");
        getContentPane().add(lblhargabukucerita);
        lblhargabukucerita.setBounds(800, 250, 60, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Bumbu");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(870, 120, 100, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/imageProduk/bumbuNasgor30000.png"))); // NOI18N
        getContentPane().add(jButton7);
        jButton7.setBounds(870, 150, 130, 100);

        lblhargabumbu.setText("Rp. 25.000");
        getContentPane().add(lblhargabumbu);
        lblhargabumbu.setBounds(940, 250, 60, 20);

        jButton29.setText("Ubah");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(30, 300, 130, 20);

        jmlbesokap.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbesokap.setText("0");
        getContentPane().add(jmlbesokap);
        jmlbesokap.setBounds(170, 270, 130, 20);

        jmlblankon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlblankon.setText("0");
        getContentPane().add(jmlblankon);
        jmlblankon.setBounds(310, 270, 130, 20);

        jButton31.setText("Ubah");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(310, 300, 130, 20);

        jButton30.setText("Ubah");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(170, 300, 130, 20);

        jmlbros.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbros.setText("0");
        getContentPane().add(jmlbros);
        jmlbros.setBounds(450, 270, 130, 20);

        jmlbukubelajar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbukubelajar.setText("0");
        getContentPane().add(jmlbukubelajar);
        jmlbukubelajar.setBounds(590, 270, 130, 20);

        jButton33.setText("Ubah");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(590, 300, 130, 20);

        jmlbukucerita.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbukucerita.setText("0");
        getContentPane().add(jmlbukucerita);
        jmlbukucerita.setBounds(730, 270, 130, 20);

        jButton34.setText("Ubah");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(730, 300, 130, 20);

        jButton32.setText("Ubah");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(450, 300, 130, 20);

        jmlbumbu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlbumbu.setText("0");
        getContentPane().add(jmlbumbu);
        jmlbumbu.setBounds(870, 270, 130, 20);

        jButton35.setText("Ubah");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(870, 300, 130, 20);

        jmlangklung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jmlangklung.setText("0");
        getContentPane().add(jmlangklung);
        jmlangklung.setBounds(30, 270, 130, 20);

        lblhargabros.setText("Rp. 25.000");
        getContentPane().add(lblhargabros);
        lblhargabros.setBounds(520, 250, 60, 20);

        lblhargablankon.setText("Rp. 25.000");
        getContentPane().add(lblhargablankon);
        lblhargablankon.setBounds(380, 250, 60, 20);

        lblhargabesokap.setText("Rp. 25.000");
        getContentPane().add(lblhargabesokap);
        lblhargabesokap.setBounds(230, 250, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bros");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 120, 50, 30);

        lblhargaangklung222.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung222.setText("Harga Lama");
        getContentPane().add(lblhargaangklung222);
        lblhargaangklung222.setBounds(870, 250, 60, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Blankon");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 120, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Angklung");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 120, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Besokap");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 120, 90, 30);

        lblhargaangklung.setText("0");
        getContentPane().add(lblhargaangklung);
        lblhargaangklung.setBounds(90, 250, 70, 20);

        lblhargaangklung3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung3.setText("Harga Lama");
        getContentPane().add(lblhargaangklung3);
        lblhargaangklung3.setBounds(170, 250, 60, 20);

        lblhargaangklung4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung4.setText("Harga Lama");
        getContentPane().add(lblhargaangklung4);
        lblhargaangklung4.setBounds(310, 250, 60, 20);

        lblhargaangklung5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung5.setText("Harga Lama");
        getContentPane().add(lblhargaangklung5);
        lblhargaangklung5.setBounds(450, 250, 60, 20);

        lblhargaangklung6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung6.setText("Harga Lama");
        getContentPane().add(lblhargaangklung6);
        lblhargaangklung6.setBounds(590, 250, 60, 20);

        lblhargaangklung7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung7.setText("Harga Lama");
        getContentPane().add(lblhargaangklung7);
        lblhargaangklung7.setBounds(730, 250, 60, 20);

        lblhargaangklung8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblhargaangklung8.setText("Harga Lama");
        getContentPane().add(lblhargaangklung8);
        lblhargaangklung8.setBounds(30, 250, 60, 20);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 40, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transbg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-170, -50, 1500, 860);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        distributorA obj = new distributorA(); // diganti
        try{
            if(Integer.parseInt(jmlangklung.getText())>0){
                obj.setDistAngklung(Integer.parseInt(jmlangklung.getText())); // diganti
                lblhargaangklung.setText("Rp. " + obj.getDistAngklung()); // diganti 
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
       distributorA obj = new distributorA();
        try{
            if(Integer.parseInt(jmlblankon.getText())>0){
                obj.setDistBlankon(Integer.parseInt(jmlblankon.getText()));
                lblhargablankon.setText("Rp. " + obj.getDistBlankon());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
      distributorA obj = new distributorA();
        try{
            if(Integer.parseInt(jmlbesokap.getText())>0){
                obj.setDistBesokap(Integer.parseInt(jmlbesokap.getText()));
                lblhargabesokap.setText("Rp. " + obj.getDistBesokap());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        distributorA obj = new distributorA();
        try{
            if(Integer.parseInt(jmlbukubelajar.getText())>0){
                obj.setDistBukuBelajar(Integer.parseInt(jmlbukubelajar.getText()));
                lblhargabukubelajar.setText("Rp. " + obj.getDistBukuBelajar());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
       distributorA obj = new distributorA();
        try{
            if(Integer.parseInt(jmlbukucerita.getText())>0){
                obj.setDistBukuCerita(Integer.parseInt(jmlbukucerita.getText()));
                lblhargabukucerita.setText("Rp. " + obj.getDistBukuCerita());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
       distributorA obj = new distributorA();
        try{
            if(Integer.parseInt(jmlbros.getText())>0){
                obj.setDistBros(Integer.parseInt(jmlbros.getText()));
                lblhargabros.setText("Rp. " + obj.getDistBros());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
       distributorA obj = new distributorA();
        try{
            if(Integer.parseInt(jmlbumbu.getText())>0){
                obj.setDistBumbu(Integer.parseInt(jmlbumbu.getText()));
                lblhargabumbu.setText("Rp. " + obj.getDistBumbu());
                alert1.showMessageDialog(null, "Harga Berhasil diubah! ", "Berhasil!", alert1.INFORMATION_MESSAGE);
            }else{
                alert1.showMessageDialog(null, "Harga Tidak Valid!", "Perhatian!!", alert1.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            alert1.showMessageDialog(null, "Input Tidak Valid", "Perhatian!", alert1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      this.setVisible(false);
        new hargadistributorframe().setVisible(true); 
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahHargaDistA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahHargaDistA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane alert1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jmlangklung;
    private javax.swing.JTextField jmlbesokap;
    private javax.swing.JTextField jmlblankon;
    private javax.swing.JTextField jmlbros;
    private javax.swing.JTextField jmlbukubelajar;
    private javax.swing.JTextField jmlbukucerita;
    private javax.swing.JTextField jmlbumbu;
    private javax.swing.JLabel lblhargaangklung;
    private javax.swing.JLabel lblhargaangklung222;
    private javax.swing.JLabel lblhargaangklung3;
    private javax.swing.JLabel lblhargaangklung4;
    private javax.swing.JLabel lblhargaangklung5;
    private javax.swing.JLabel lblhargaangklung6;
    private javax.swing.JLabel lblhargaangklung7;
    private javax.swing.JLabel lblhargaangklung8;
    private javax.swing.JLabel lblhargabesokap;
    private javax.swing.JLabel lblhargablankon;
    private javax.swing.JLabel lblhargabros;
    private javax.swing.JLabel lblhargabukubelajar;
    private javax.swing.JLabel lblhargabukucerita;
    private javax.swing.JLabel lblhargabumbu;
    // End of variables declaration//GEN-END:variables
}
