/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli.distributor.customer;

/**
 *
 * @author thero
 */
public class laporanCustomer extends javax.swing.JFrame {

    /**
     * Creates new form laporanCustomer
     */
    public laporanCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtkonfirm = new javax.swing.JTextArea();
        txtCustomer = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        comboDist = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmlTransaksi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);

        txtkonfirm.setColumns(20);
        txtkonfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonfirm.setRows(5);
        txtkonfirm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(txtkonfirm);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 120, 440, 450);

        txtCustomer.setEditable(true);
        txtCustomer.setFont(new java.awt.Font("UniSansBold", 0, 36)); // NOI18N
        txtCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer A", "Customer B", "Customer C", "Customer D", "Customer E" }));
        getContentPane().add(txtCustomer);
        txtCustomer.setBounds(30, 120, 230, 50);

        jButton1.setText("Back");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 100, 40);

        comboDist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(comboDist);
        comboDist.setBounds(30, 240, 230, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 310, 230, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Transaksi Ke-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 200, 150, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(790, 280, 220, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Total Pengeluaran");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(790, 240, 230, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Jumlah Transaksi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(790, 120, 210, 30);
        getContentPane().add(jmlTransaksi);
        jmlTransaksi.setBounds(790, 160, 220, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      /*  try{
            transaksi = "";
            txtkonfirm.setText("");
            pembelian obj = new pembelian();
            String distributor = distributorname.getSelectedItem().toString();
            String indexText = comboDist.getSelectedItem().toString();
            //alert1.showMessageDialog(null, indexText , "Berhasil!", alert1.INFORMATION_MESSAGE);
            int indexa = Integer.parseInt(indexText);
            if(distributor.equals("DISTRIBUTOR A")){
                transaksi = String.join("\n", obj.listPembelianDistributorA.get(indexa-1));
            }
            else if (distributor.equals("DISTRIBUTOR B")){
                transaksi = String.join("\n", obj.listPembelianDistributorB.get(indexa-1));
            }
            else if (distributor.equals("DISTRIBUTOR C")){
                transaksi = String.join("\n", obj.listPembelianDistributorC.get(indexa-1));
            }
            else if (distributor.equals("DISTRIBUTOR D")){
                transaksi = String.join("\n", obj.listPembelianDistributorD.get(indexa-1));
            }
            //  alert1.showMessageDialog(null, Arrays.toString(obj.listPembelianDistributorA.toArray()) , "Berhasil!", alert1.INFORMATION_MESSAGE);
            txtkonfirm.append(transaksi);
        }
        catch(IndexOutOfBoundsException e){
            alert1.showMessageDialog(null, "Tidak ada Index!" , "PERHATIAN!", alert1.INFORMATION_MESSAGE);
        }
*/
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jmlTransaksi;
    private javax.swing.JComboBox<String> txtCustomer;
    private javax.swing.JTextArea txtkonfirm;
    // End of variables declaration//GEN-END:variables
}
