/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuli;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import laporan.penjualanFrame;
import laporan.semualaporanFame;
import manageproduk.ubahHargaProdukFrame;
import meuli.distributor.customer.akun.aboutus;
import meuli.distributor.customer.akun.developer;
import meuli.distributor.customer.akun.personalisasiFrame;
import meuli.distributor.customer.akun.personalisasiFrameOwner;
import meuli.distributor.distributorframe;
import meuli.distributor.hargadistributorframe;

/**
 *
 * @author thero
 */
public class ownerFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminHome
     */
    public ownerFrame() {
        initComponents();
        developer yow = new developer();
      //  txtusername.setText(yow.nama);
        
        lbltransaksi.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new transaction().setVisible(true);}}); 
      
        lblpesanbarang.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new distributorframe().setVisible(true);}}); 
        
        lblgantiharga.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new ubahHargaProdukFrame().setVisible(true);}}); 
        
        
       
        lbllaporan.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new semualaporanFame().setVisible(true);}});
        lbldashboard.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new penjualanFrame().setVisible(true);}});
        
        lbllogout.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new login().setVisible(true);}});
        lblabout.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new aboutus().setVisible(true);}});
        
        lblpersonalisasi.addMouseListener(new MouseAdapter(){  
            public void mouseClicked(MouseEvent e)
                    {
                        close();
                        new personalisasiFrameOwner().setVisible(true);}});

// you can open a new frame here as
// i have assumed you have declared "frame" as instance variable
    


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JLabel();
        lblpesanbarang = new javax.swing.JLabel();
        lbltransaksi = new javax.swing.JLabel();
        lblgantiharga = new javax.swing.JLabel();
        lbllaporan = new javax.swing.JLabel();
        lblpersonalisasi = new javax.swing.JLabel();
        lbldashboard = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        lblabout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 850));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Raleway SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Halo,");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1030, 60, 60, 30);

        txtusername.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("Owner");
        getContentPane().add(txtusername);
        txtusername.setBounds(1090, 60, 180, 30);

        lblpesanbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/pesanBarang.png"))); // NOI18N
        getContentPane().add(lblpesanbarang);
        lblpesanbarang.setBounds(330, 140, 280, 320);

        lbltransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/transaksiPembelian.png"))); // NOI18N
        getContentPane().add(lbltransaksi);
        lbltransaksi.setBounds(50, 140, 280, 320);

        lblgantiharga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/ubahharga.png"))); // NOI18N
        getContentPane().add(lblgantiharga);
        lblgantiharga.setBounds(610, 140, 280, 320);

        lbllaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/laporan.png"))); // NOI18N
        getContentPane().add(lbllaporan);
        lbllaporan.setBounds(50, 470, 550, 300);

        lblpersonalisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/person.png"))); // NOI18N
        getContentPane().add(lblpersonalisasi);
        lblpersonalisasi.setBounds(890, 140, 280, 310);

        lbldashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/dashboard.png"))); // NOI18N
        getContentPane().add(lbldashboard);
        lbldashboard.setBounds(610, 470, 280, 290);

        lbllogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/logout.png"))); // NOI18N
        getContentPane().add(lbllogout);
        lbllogout.setBounds(1170, 470, 280, 290);

        lblabout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/about.png"))); // NOI18N
        getContentPane().add(lblabout);
        lblabout.setBounds(890, 470, 280, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meuli/image/BackGroundMenu.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1490, 840);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerFrame().setVisible(true);
                
                
            }
        });
    }
    
    public void close(){
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblabout;
    private javax.swing.JLabel lbldashboard;
    private javax.swing.JLabel lblgantiharga;
    private javax.swing.JLabel lbllaporan;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblpersonalisasi;
    private javax.swing.JLabel lblpesanbarang;
    private javax.swing.JLabel lbltransaksi;
    private javax.swing.JLabel txtusername;
    // End of variables declaration//GEN-END:variables
}
